"""Activity implementations for calculate_vector_cosine_similarity.

Generated by CompiledAI Workflow Factory.
"""

from typing import List
import math


def calculate_cosine_similarity(vectorA: List[float], vectorB: List[float]) -> float:
    """Calculate the cosine similarity between two vectors.
    
    Computes the dot product divided by the product of their magnitudes.
    Cosine similarity measures the cosine of the angle between two vectors,
    returning a value between -1 and 1, where 1 indicates identical direction.
    
    Args:
        vectorA: The first vector containing float values representing feature measurements.
        vectorB: The second vector containing float values representing feature measurements.
        
    Returns:
        The cosine similarity score between the two vectors, ranging from -1
        (opposite) to 1 (identical).
        
    Raises:
        TypeError: If vectorA or vectorB is not a list.
        ValueError: If vectors are empty or have different lengths.
        ValueError: If vectors contain non-numeric values.
        ValueError: If either vector is a zero vector (magnitude is 0).
    """
    # Type validation
    if not isinstance(vectorA, list):
        raise TypeError(f"vectorA must be a list, got {type(vectorA).__name__}")
    if not isinstance(vectorB, list):
        raise TypeError(f"vectorB must be a list, got {type(vectorB).__name__}")
    
    # Empty check
    if len(vectorA) == 0:
        raise ValueError("vectorA cannot be empty")
    if len(vectorB) == 0:
        raise ValueError("vectorB cannot be empty")
    
    # Length check
    if len(vectorA) != len(vectorB):
        raise ValueError(
            f"Vectors must have the same length, got {len(vectorA)} and {len(vectorB)}"
        )
    
    # Validate numeric values
    for i, val in enumerate(vectorA):
        if not isinstance(val, (int, float)):
            raise ValueError(f"vectorA[{i}] must be numeric, got {type(val).__name__}")
    for i, val in enumerate(vectorB):
        if not isinstance(val, (int, float)):
            raise ValueError(f"vectorB[{i}] must be numeric, got {type(val).__name__}")
    
    # Calculate dot product
    dot_product = sum(a * b for a, b in zip(vectorA, vectorB))
    
    # Calculate magnitudes
    magnitude_a = math.sqrt(sum(a * a for a in vectorA))
    magnitude_b = math.sqrt(sum(b * b for b in vectorB))
    
    # Zero vector check
    if magnitude_a == 0:
        raise ValueError("vectorA is a zero vector (magnitude is 0)")
    if magnitude_b == 0:
        raise ValueError("vectorB is a zero vector (magnitude is 0)")
    
    # Calculate cosine similarity
    similarity = dot_product / (magnitude_a * magnitude_b)
    
    return similarity


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Normal case with default values from workflow
        vectorA = [0.5, 0.7, 0.2, 0.9, 0.1]
        vectorB = [0.4, 0.6, 0.3, 0.8, 0.2]
        result1 = calculate_cosine_similarity(vectorA, vectorB)
        assert isinstance(result1, float), "Result should be a float"
        assert -1 <= result1 <= 1, f"Cosine similarity should be between -1 and 1, got {result1}"
        print(f"  ✓ calculate_cosine_similarity (normal): {result1:.6f}")
        
        # Test 2: Identical vectors should return 1.0
        identical_vec = [1.0, 2.0, 3.0]
        result2 = calculate_cosine_similarity(identical_vec, identical_vec)
        assert abs(result2 - 1.0) < 1e-9, f"Identical vectors should have similarity 1.0, got {result2}"
        print(f"  ✓ calculate_cosine_similarity (identical): {result2:.6f}")
        
        # Test 3: Opposite vectors should return -1.0
        vec_pos = [1.0, 2.0, 3.0]
        vec_neg = [-1.0, -2.0, -3.0]
        result3 = calculate_cosine_similarity(vec_pos, vec_neg)
        assert abs(result3 - (-1.0)) < 1e-9, f"Opposite vectors should have similarity -1.0, got {result3}"
        print(f"  ✓ calculate_cosine_similarity (opposite): {result3:.6f}")
        
        # Test 4: Orthogonal vectors should return 0.0
        vec_x = [1.0, 0.0]
        vec_y = [0.0, 1.0]
        result4 = calculate_cosine_similarity(vec_x, vec_y)
        assert abs(result4) < 1e-9, f"Orthogonal vectors should have similarity 0.0, got {result4}"
        print(f"  ✓ calculate_cosine_similarity (orthogonal): {result4:.6f}")
        
        # Test 5: TypeError for non-list input
        try:
            calculate_cosine_similarity("not a list", [1.0, 2.0])
            assert False, "Should have raised TypeError"
        except TypeError as e:
            assert "vectorA must be a list" in str(e)
            print(f"  ✓ calculate_cosine_similarity (TypeError): caught correctly")
        
        # Test 6: ValueError for empty vectors
        try:
            calculate_cosine_similarity([], [1.0, 2.0])
            assert False, "Should have raised ValueError"
        except ValueError as e:
            assert "cannot be empty" in str(e)
            print(f"  ✓ calculate_cosine_similarity (empty vector): caught correctly")
        
        # Test 7: ValueError for different lengths
        try:
            calculate_cosine_similarity([1.0, 2.0], [1.0, 2.0, 3.0])
            assert False, "Should have raised ValueError"
        except ValueError as e:
            assert "same length" in str(e)
            print(f"  ✓ calculate_cosine_similarity (length mismatch): caught correctly")
        
        # Test 8: ValueError for zero vector
        try:
            calculate_cosine_similarity([0.0, 0.0, 0.0], [1.0, 2.0, 3.0])
            assert False, "Should have raised ValueError"
        except ValueError as e:
            assert "zero vector" in str(e)
            print(f"  ✓ calculate_cosine_similarity (zero vector): caught correctly")
        
        # Test 9: Integer inputs should work
        result9 = calculate_cosine_similarity([1, 2, 3], [4, 5, 6])
        assert isinstance(result9, float), "Result should be a float even with int inputs"
        print(f"  ✓ calculate_cosine_similarity (integer inputs): {result9:.6f}")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
