"""Activity implementations for calculate_electrostatic_potential_energy_workflow.

Generated by CompiledAI Workflow Factory.
"""

from typing import Union


def calculate_electrostatic_potential_energy(charge: float, voltage: float) -> float:
    """Calculate the electrostatic potential energy using U = charge * voltage.
    
    Computes the electrostatic potential energy for a charged particle in an
    electric field using the formula U = q * V, where q is the charge in
    coulombs and V is the voltage (potential difference) in volts.
    
    Args:
        charge: The charge of the object, in coulombs.
        voltage: The voltage of the object, in volts.
        
    Returns:
        The electrostatic potential energy in joules.
        
    Raises:
        TypeError: If charge or voltage is not a numeric type (int or float).
    """
    # Input validation - check types
    if not isinstance(charge, (int, float)):
        raise TypeError(f"charge must be a numeric type (int or float), got {type(charge).__name__}")
    if not isinstance(voltage, (int, float)):
        raise TypeError(f"voltage must be a numeric type (int or float), got {type(voltage).__name__}")
    
    # Check for NaN or infinity
    if isinstance(charge, float) and (charge != charge or abs(charge) == float('inf')):
        raise ValueError("charge must be a finite number, not NaN or infinity")
    if isinstance(voltage, float) and (voltage != voltage or abs(voltage) == float('inf')):
        raise ValueError("voltage must be a finite number, not NaN or infinity")
    
    # Calculate electrostatic potential energy: U = q * V
    potential_energy = charge * voltage
    
    return float(potential_energy)


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Basic positive values
        result1 = calculate_electrostatic_potential_energy(charge=2.0, voltage=5.0)
        assert result1 == 10.0, f"Expected 10.0, got {result1}"
        print(f"  ✓ calculate_electrostatic_potential_energy(2.0, 5.0): {result1} J")
        
        # Test 2: Negative charge (electron-like)
        result2 = calculate_electrostatic_potential_energy(charge=-1.6e-19, voltage=100.0)
        expected2 = -1.6e-17
        assert abs(result2 - expected2) < 1e-30, f"Expected {expected2}, got {result2}"
        print(f"  ✓ calculate_electrostatic_potential_energy(-1.6e-19, 100.0): {result2} J")
        
        # Test 3: Zero charge
        result3 = calculate_electrostatic_potential_energy(charge=0.0, voltage=1000.0)
        assert result3 == 0.0, f"Expected 0.0, got {result3}"
        print(f"  ✓ calculate_electrostatic_potential_energy(0.0, 1000.0): {result3} J")
        
        # Test 4: Zero voltage
        result4 = calculate_electrostatic_potential_energy(charge=5.0, voltage=0.0)
        assert result4 == 0.0, f"Expected 0.0, got {result4}"
        print(f"  ✓ calculate_electrostatic_potential_energy(5.0, 0.0): {result4} J")
        
        # Test 5: Integer inputs (should work and return float)
        result5 = calculate_electrostatic_potential_energy(charge=3, voltage=4)
        assert result5 == 12.0, f"Expected 12.0, got {result5}"
        assert isinstance(result5, float), f"Expected float, got {type(result5).__name__}"
        print(f"  ✓ calculate_electrostatic_potential_energy(3, 4): {result5} J (int inputs)")
        
        # Test 6: Negative voltage
        result6 = calculate_electrostatic_potential_energy(charge=2.0, voltage=-10.0)
        assert result6 == -20.0, f"Expected -20.0, got {result6}"
        print(f"  ✓ calculate_electrostatic_potential_energy(2.0, -10.0): {result6} J")
        
        # Test 7: Type error for non-numeric charge
        try:
            calculate_electrostatic_potential_energy(charge="5", voltage=10.0)
            assert False, "Expected TypeError for string charge"
        except TypeError as e:
            assert "charge must be a numeric type" in str(e)
            print(f"  ✓ TypeError raised for string charge: {e}")
        
        # Test 8: Type error for non-numeric voltage
        try:
            calculate_electrostatic_potential_energy(charge=5.0, voltage=None)
            assert False, "Expected TypeError for None voltage"
        except TypeError as e:
            assert "voltage must be a numeric type" in str(e)
            print(f"  ✓ TypeError raised for None voltage: {e}")
        
        # Test 9: ValueError for NaN
        try:
            calculate_electrostatic_potential_energy(charge=float('nan'), voltage=10.0)
            assert False, "Expected ValueError for NaN charge"
        except ValueError as e:
            assert "finite number" in str(e)
            print(f"  ✓ ValueError raised for NaN charge: {e}")
        
        # Test 10: ValueError for infinity
        try:
            calculate_electrostatic_potential_energy(charge=5.0, voltage=float('inf'))
            assert False, "Expected ValueError for infinite voltage"
        except ValueError as e:
            assert "finite number" in str(e)
            print(f"  ✓ ValueError raised for infinite voltage: {e}")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
