"""Activity implementations for calculate_vector_cosine_similarities.

Generated by CompiledAI Workflow Factory.
"""

from typing import List
import math


def calculate_cosine_similarity(vectorA: List[float], vectorB: List[float]) -> float:
    """Calculate the cosine similarity between two vectors.
    
    Returns a value between -1 and 1, where 1 indicates identical direction,
    0 indicates orthogonality, and -1 indicates opposite directions.
    
    Args:
        vectorA: The first vector as a list of float values
        vectorB: The second vector as a list of float values (must have same length as vectorA)
        
    Returns:
        The cosine similarity value between the two vectors
        
    Raises:
        TypeError: If vectorA or vectorB is not a list
        ValueError: If vectors are empty or have different lengths
        ValueError: If vectors contain non-numeric values
        ValueError: If both vectors are zero vectors (undefined similarity)
    """
    # Type validation
    if not isinstance(vectorA, list):
        raise TypeError(f"vectorA must be a list, got {type(vectorA).__name__}")
    if not isinstance(vectorB, list):
        raise TypeError(f"vectorB must be a list, got {type(vectorB).__name__}")
    
    # Empty check
    if len(vectorA) == 0:
        raise ValueError("vectorA cannot be empty")
    if len(vectorB) == 0:
        raise ValueError("vectorB cannot be empty")
    
    # Length check
    if len(vectorA) != len(vectorB):
        raise ValueError(
            f"Vectors must have the same length, got {len(vectorA)} and {len(vectorB)}"
        )
    
    # Validate numeric values
    for i, val in enumerate(vectorA):
        if not isinstance(val, (int, float)):
            raise ValueError(f"vectorA[{i}] must be numeric, got {type(val).__name__}")
    for i, val in enumerate(vectorB):
        if not isinstance(val, (int, float)):
            raise ValueError(f"vectorB[{i}] must be numeric, got {type(val).__name__}")
    
    # Calculate dot product and magnitudes
    dot_product = sum(a * b for a, b in zip(vectorA, vectorB))
    magnitude_a = math.sqrt(sum(a * a for a in vectorA))
    magnitude_b = math.sqrt(sum(b * b for b in vectorB))
    
    # Check for zero vectors
    if magnitude_a == 0 and magnitude_b == 0:
        raise ValueError("Cosine similarity is undefined for two zero vectors")
    if magnitude_a == 0:
        raise ValueError("Cosine similarity is undefined when vectorA is a zero vector")
    if magnitude_b == 0:
        raise ValueError("Cosine similarity is undefined when vectorB is a zero vector")
    
    # Calculate cosine similarity
    similarity = dot_product / (magnitude_a * magnitude_b)
    
    # Clamp to [-1, 1] to handle floating point errors
    similarity = max(-1.0, min(1.0, similarity))
    
    return similarity


if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Basic similarity calculation (similar vectors)
        result1 = calculate_cosine_similarity(
            [0.5, 0.7, 0.2, 0.9, 0.1],
            [0.3, 0.6, 0.2, 0.8, 0.1]
        )
        assert -1 <= result1 <= 1, f"Result should be in [-1, 1], got {result1}"
        assert result1 > 0.9, f"Similar vectors should have high similarity, got {result1}"
        print(f"  ✓ calculate_cosine_similarity (similar): {result1:.6f}")
        
        # Test 2: Identical vectors (should be 1.0)
        result2 = calculate_cosine_similarity([1, 2, 3], [1, 2, 3])
        assert abs(result2 - 1.0) < 1e-9, f"Identical vectors should have similarity 1.0, got {result2}"
        print(f"  ✓ calculate_cosine_similarity (identical): {result2:.6f}")
        
        # Test 3: Opposite vectors (should be -1.0)
        result3 = calculate_cosine_similarity([1, 2, 3], [-1, -2, -3])
        assert abs(result3 - (-1.0)) < 1e-9, f"Opposite vectors should have similarity -1.0, got {result3}"
        print(f"  ✓ calculate_cosine_similarity (opposite): {result3:.6f}")
        
        # Test 4: Orthogonal vectors (should be 0.0)
        result4 = calculate_cosine_similarity([1, 0], [0, 1])
        assert abs(result4) < 1e-9, f"Orthogonal vectors should have similarity 0.0, got {result4}"
        print(f"  ✓ calculate_cosine_similarity (orthogonal): {result4:.6f}")
        
        # Test 5: Sample data from workflow spec
        pairs = [
            {"vectorA": [0.5, 0.7, 0.2, 0.9, 0.1], "vectorB": [0.3, 0.6, 0.2, 0.8, 0.1]},
            {"vectorA": [0.2, 0.4, 0.6, 0.8, 1.0], "vectorB": [1.0, 0.8, 0.6, 0.4, 0.2]},
            {"vectorA": [0.1, 0.2, 0.3, 0.4, 0.5], "vectorB": [0.5, 0.4, 0.3, 0.2, 0.1]},
        ]
        for i, pair in enumerate(pairs):
            result = calculate_cosine_similarity(pair["vectorA"], pair["vectorB"])
            assert -1 <= result <= 1, f"Result should be in [-1, 1], got {result}"
            print(f"  ✓ calculate_cosine_similarity (pair {i+1}): {result:.6f}")
        
        # Test 6: Error handling - different lengths
        try:
            calculate_cosine_similarity([1, 2], [1, 2, 3])
            assert False, "Should have raised ValueError for different lengths"
        except ValueError as e:
            assert "same length" in str(e)
            print(f"  ✓ calculate_cosine_similarity (length error): caught correctly")
        
        # Test 7: Error handling - empty vectors
        try:
            calculate_cosine_similarity([], [])
            assert False, "Should have raised ValueError for empty vectors"
        except ValueError as e:
            assert "empty" in str(e)
            print(f"  ✓ calculate_cosine_similarity (empty error): caught correctly")
        
        # Test 8: Error handling - zero vector
        try:
            calculate_cosine_similarity([0, 0, 0], [1, 2, 3])
            assert False, "Should have raised ValueError for zero vector"
        except ValueError as e:
            assert "zero vector" in str(e)
            print(f"  ✓ calculate_cosine_similarity (zero vector error): caught correctly")
        
        # Test 9: Error handling - invalid type
        try:
            calculate_cosine_similarity("not a list", [1, 2, 3])
            assert False, "Should have raised TypeError for invalid type"
        except TypeError as e:
            assert "must be a list" in str(e)
            print(f"  ✓ calculate_cosine_similarity (type error): caught correctly")
        
        # Test 10: Error handling - non-numeric values
        try:
            calculate_cosine_similarity([1, "two", 3], [1, 2, 3])
            assert False, "Should have raised ValueError for non-numeric values"
        except ValueError as e:
            assert "numeric" in str(e)
            print(f"  ✓ calculate_cosine_similarity (numeric error): caught correctly")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
