"""Activity implementations for calculate_object_density.

Generated by CompiledAI Workflow Factory.
"""

from typing import Union


def calculate_density(mass: float, volume: float) -> float:
    """Calculate the density of an object by dividing mass by volume.

    Uses the formula: density = mass / volume.

    Args:
        mass: The mass of the object, in kilograms.
        volume: The volume of the object, in cubic meters.

    Returns:
        The calculated density in kilograms per cubic meter (kg/m³).

    Raises:
        TypeError: If mass or volume is not a numeric type.
        ValueError: If mass is negative or volume is zero/negative.
    """
    # Type validation
    if not isinstance(mass, (int, float)):
        raise TypeError(f"mass must be a number, got {type(mass).__name__}")
    if not isinstance(volume, (int, float)):
        raise TypeError(f"volume must be a number, got {type(volume).__name__}")

    # Value validation
    if mass < 0:
        raise ValueError(f"mass must be non-negative, got {mass}")
    if volume <= 0:
        raise ValueError(f"volume must be positive, got {volume}")

    # Calculate density
    density = mass / volume

    return density


if __name__ == "__main__":
    import sys

    print("Testing activities...")

    try:
        # Test normal case
        result = calculate_density(50.0, 10.0)
        assert result == 5.0, f"Expected 5.0, got {result}"
        print(f"  ✓ calculate_density(50.0, 10.0): {result} kg/m³")

        # Test with integers
        result_int = calculate_density(100, 25)
        assert result_int == 4.0, f"Expected 4.0, got {result_int}"
        print(f"  ✓ calculate_density(100, 25): {result_int} kg/m³")

        # Test with zero mass
        result_zero_mass = calculate_density(0.0, 5.0)
        assert result_zero_mass == 0.0, f"Expected 0.0, got {result_zero_mass}"
        print(f"  ✓ calculate_density(0.0, 5.0): {result_zero_mass} kg/m³")

        # Test edge case: small volume
        result_small = calculate_density(1.0, 0.001)
        assert result_small == 1000.0, f"Expected 1000.0, got {result_small}"
        print(f"  ✓ calculate_density(1.0, 0.001): {result_small} kg/m³")

        # Test error case: zero volume
        try:
            calculate_density(10.0, 0.0)
            assert False, "Should have raised ValueError for zero volume"
        except ValueError as e:
            print(f"  ✓ Correctly raises ValueError for zero volume: {e}")

        # Test error case: negative volume
        try:
            calculate_density(10.0, -5.0)
            assert False, "Should have raised ValueError for negative volume"
        except ValueError as e:
            print(f"  ✓ Correctly raises ValueError for negative volume: {e}")

        # Test error case: negative mass
        try:
            calculate_density(-10.0, 5.0)
            assert False, "Should have raised ValueError for negative mass"
        except ValueError as e:
            print(f"  ✓ Correctly raises ValueError for negative mass: {e}")

        # Test error case: invalid type for mass
        try:
            calculate_density("50", 10.0)
            assert False, "Should have raised TypeError for string mass"
        except TypeError as e:
            print(f"  ✓ Correctly raises TypeError for invalid mass type: {e}")

        # Test error case: invalid type for volume
        try:
            calculate_density(50.0, None)
            assert False, "Should have raised TypeError for None volume"
        except TypeError as e:
            print(f"  ✓ Correctly raises TypeError for invalid volume type: {e}")

        print("\nAll tests passed! ✅")

    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
