"""Activity implementations for calculate_feature_vector_cosine_similarity.

Generated by CompiledAI Workflow Factory.
"""

from typing import List
import math


def calculate_cosine_similarity(vectorA: List[float], vectorB: List[float]) -> float:
    """Calculate the cosine similarity between two vectors.
    
    Computes the cosine similarity by calculating the dot product divided by
    the product of their magnitudes. The result ranges from -1 (opposite) to
    1 (identical direction).
    
    Args:
        vectorA: The first vector containing float values representing feature characteristics.
        vectorB: The second vector containing float values representing feature characteristics.
        
    Returns:
        The cosine similarity score between the two vectors, ranging from -1 to 1.
        
    Raises:
        TypeError: If inputs are not lists or contain non-numeric values.
        ValueError: If vectors are empty or have different lengths.
    """
    # Input validation - type checking
    if not isinstance(vectorA, list):
        raise TypeError(f"vectorA must be a list, got {type(vectorA).__name__}")
    if not isinstance(vectorB, list):
        raise TypeError(f"vectorB must be a list, got {type(vectorB).__name__}")
    
    # Check for empty vectors
    if len(vectorA) == 0:
        raise ValueError("vectorA cannot be empty")
    if len(vectorB) == 0:
        raise ValueError("vectorB cannot be empty")
    
    # Check vectors have same length
    if len(vectorA) != len(vectorB):
        raise ValueError(
            f"Vectors must have the same length, got {len(vectorA)} and {len(vectorB)}"
        )
    
    # Validate all elements are numeric
    for i, val in enumerate(vectorA):
        if not isinstance(val, (int, float)):
            raise TypeError(f"vectorA[{i}] must be numeric, got {type(val).__name__}")
    for i, val in enumerate(vectorB):
        if not isinstance(val, (int, float)):
            raise TypeError(f"vectorB[{i}] must be numeric, got {type(val).__name__}")
    
    # Calculate dot product
    dot_product = sum(a * b for a, b in zip(vectorA, vectorB))
    
    # Calculate magnitudes
    magnitude_a = math.sqrt(sum(a * a for a in vectorA))
    magnitude_b = math.sqrt(sum(b * b for b in vectorB))
    
    # Handle zero magnitude vectors
    if magnitude_a == 0 or magnitude_b == 0:
        raise ValueError("Cannot compute cosine similarity for zero-magnitude vector")
    
    # Calculate cosine similarity
    similarity = dot_product / (magnitude_a * magnitude_b)
    
    # Clamp result to [-1, 1] to handle floating point errors
    return max(-1.0, min(1.0, similarity))


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test with default workflow values
        vectorA = [0.5, 0.7, 0.2, 0.9, 0.1]
        vectorB = [0.4, 0.6, 0.3, 0.8, 0.2]
        result = calculate_cosine_similarity(vectorA, vectorB)
        assert isinstance(result, float), f"Expected float, got {type(result).__name__}"
        assert -1 <= result <= 1, f"Result {result} out of range [-1, 1]"
        print(f"  ✓ calculate_cosine_similarity(default): {result:.6f}")
        
        # Test identical vectors (should be 1.0)
        identical = [1.0, 2.0, 3.0]
        result_identical = calculate_cosine_similarity(identical, identical)
        assert abs(result_identical - 1.0) < 1e-9, f"Identical vectors should have similarity 1.0, got {result_identical}"
        print(f"  ✓ calculate_cosine_similarity(identical): {result_identical}")
        
        # Test opposite vectors (should be -1.0)
        vec1 = [1.0, 0.0]
        vec2 = [-1.0, 0.0]
        result_opposite = calculate_cosine_similarity(vec1, vec2)
        assert abs(result_opposite - (-1.0)) < 1e-9, f"Opposite vectors should have similarity -1.0, got {result_opposite}"
        print(f"  ✓ calculate_cosine_similarity(opposite): {result_opposite}")
        
        # Test orthogonal vectors (should be 0.0)
        vec_orth1 = [1.0, 0.0]
        vec_orth2 = [0.0, 1.0]
        result_orthogonal = calculate_cosine_similarity(vec_orth1, vec_orth2)
        assert abs(result_orthogonal) < 1e-9, f"Orthogonal vectors should have similarity 0.0, got {result_orthogonal}"
        print(f"  ✓ calculate_cosine_similarity(orthogonal): {result_orthogonal}")
        
        # Test error handling - different lengths
        try:
            calculate_cosine_similarity([1.0, 2.0], [1.0, 2.0, 3.0])
            assert False, "Should have raised ValueError for different lengths"
        except ValueError as e:
            print(f"  ✓ ValueError for different lengths: {e}")
        
        # Test error handling - empty vector
        try:
            calculate_cosine_similarity([], [1.0])
            assert False, "Should have raised ValueError for empty vector"
        except ValueError as e:
            print(f"  ✓ ValueError for empty vector: {e}")
        
        # Test error handling - non-list input
        try:
            calculate_cosine_similarity("not a list", [1.0])
            assert False, "Should have raised TypeError for non-list"
        except TypeError as e:
            print(f"  ✓ TypeError for non-list: {e}")
        
        # Test error handling - zero vector
        try:
            calculate_cosine_similarity([0.0, 0.0], [1.0, 1.0])
            assert False, "Should have raised ValueError for zero vector"
        except ValueError as e:
            print(f"  ✓ ValueError for zero vector: {e}")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
