"""Activity implementations for dice_binomial_probability.

Generated by CompiledAI Workflow Factory.
"""

from typing import Union
import math


def calc_binomial_probability(n: int, k: int, p: float) -> float:
    """Calculate the binomial probability of getting exactly k successes in n trials.
    
    Uses the binomial probability formula:
    P(X=k) = C(n,k) * p^k * (1-p)^(n-k)
    
    where C(n,k) is the binomial coefficient "n choose k".
    
    Args:
        n: The number of trials (dice rolls). Must be a non-negative integer.
        k: The number of successes (times landing on target). Must be 0 <= k <= n.
        p: The probability of success on each trial. Must be 0 <= p <= 1.
        
    Returns:
        The probability of getting exactly k successes in n trials.
        
    Raises:
        TypeError: If n or k are not integers, or if p is not a number.
        ValueError: If n < 0, k < 0, k > n, or p is not in [0, 1].
    """
    # Type validation
    if not isinstance(n, int):
        raise TypeError(f"n must be int, got {type(n).__name__}")
    if not isinstance(k, int):
        raise TypeError(f"k must be int, got {type(k).__name__}")
    if not isinstance(p, (int, float)):
        raise TypeError(f"p must be a number, got {type(p).__name__}")
    
    # Value validation
    if n < 0:
        raise ValueError(f"n must be non-negative, got {n}")
    if k < 0:
        raise ValueError(f"k must be non-negative, got {k}")
    if k > n:
        raise ValueError(f"k ({k}) cannot be greater than n ({n})")
    if not 0 <= p <= 1:
        raise ValueError(f"p must be between 0 and 1, got {p}")
    
    # Calculate binomial coefficient C(n, k) = n! / (k! * (n-k)!)
    binomial_coeff = math.comb(n, k)
    
    # Calculate probability: C(n,k) * p^k * (1-p)^(n-k)
    probability = binomial_coeff * (p ** k) * ((1 - p) ** (n - k))
    
    return probability


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Main use case - probability of 5 sixes in 20 dice rolls
        result1 = calc_binomial_probability(n=20, k=5, p=1/6)
        expected1 = 0.1294  # Approximately 12.94%
        assert 0.129 < result1 < 0.130, f"Expected ~0.1294, got {result1}"
        print(f"  ✓ calc_binomial_probability(20, 5, 1/6): {result1:.6f}")
        
        # Test 2: Edge case - k = 0 (no successes)
        result2 = calc_binomial_probability(n=10, k=0, p=0.5)
        expected2 = 0.5 ** 10  # (1-0.5)^10
        assert abs(result2 - expected2) < 1e-10, f"Expected {expected2}, got {result2}"
        print(f"  ✓ calc_binomial_probability(10, 0, 0.5): {result2:.6f}")
        
        # Test 3: Edge case - k = n (all successes)
        result3 = calc_binomial_probability(n=5, k=5, p=0.3)
        expected3 = 0.3 ** 5
        assert abs(result3 - expected3) < 1e-10, f"Expected {expected3}, got {result3}"
        print(f"  ✓ calc_binomial_probability(5, 5, 0.3): {result3:.6f}")
        
        # Test 4: Edge case - p = 0 (impossible success)
        result4 = calc_binomial_probability(n=10, k=0, p=0)
        assert result4 == 1.0, f"Expected 1.0, got {result4}"
        print(f"  ✓ calc_binomial_probability(10, 0, 0): {result4}")
        
        # Test 5: Edge case - p = 1 (guaranteed success)
        result5 = calc_binomial_probability(n=10, k=10, p=1)
        assert result5 == 1.0, f"Expected 1.0, got {result5}"
        print(f"  ✓ calc_binomial_probability(10, 10, 1): {result5}")
        
        # Test 6: n = 0 trials
        result6 = calc_binomial_probability(n=0, k=0, p=0.5)
        assert result6 == 1.0, f"Expected 1.0, got {result6}"
        print(f"  ✓ calc_binomial_probability(0, 0, 0.5): {result6}")
        
        # Test 7: Type error - n not int
        try:
            calc_binomial_probability(n=10.5, k=5, p=0.5)
            assert False, "Should have raised TypeError"
        except TypeError as e:
            print(f"  ✓ TypeError for float n: {e}")
        
        # Test 8: Value error - k > n
        try:
            calc_binomial_probability(n=5, k=10, p=0.5)
            assert False, "Should have raised ValueError"
        except ValueError as e:
            print(f"  ✓ ValueError for k > n: {e}")
        
        # Test 9: Value error - p out of range
        try:
            calc_binomial_probability(n=10, k=5, p=1.5)
            assert False, "Should have raised ValueError"
        except ValueError as e:
            print(f"  ✓ ValueError for p > 1: {e}")
        
        # Test 10: Value error - negative n
        try:
            calc_binomial_probability(n=-5, k=2, p=0.5)
            assert False, "Should have raised ValueError"
        except ValueError as e:
            print(f"  ✓ ValueError for negative n: {e}")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
