"""Activity implementations for calculate_object_density.

Generated by CompiledAI Workflow Factory.
"""

from typing import Union


def calculate_density(mass: float, volume: float) -> float:
    """Calculate the density of an object by dividing mass by volume.
    
    Density is computed as mass divided by volume, returning the result
    in kilograms per cubic meter (kg/m³).
    
    Args:
        mass: The mass of the object, in kilograms.
        volume: The volume of the object, in cubic meters.
        
    Returns:
        The calculated density in kilograms per cubic meter (kg/m³).
        
    Raises:
        TypeError: If mass or volume is not a numeric type (int or float).
        ValueError: If mass is negative, or if volume is zero or negative.
    """
    # Input validation - type checking
    if not isinstance(mass, (int, float)):
        raise TypeError(f"mass must be a number, got {type(mass).__name__}")
    if not isinstance(volume, (int, float)):
        raise TypeError(f"volume must be a number, got {type(volume).__name__}")
    
    # Input validation - value checking
    if mass < 0:
        raise ValueError(f"mass must be non-negative, got {mass}")
    if volume <= 0:
        raise ValueError(f"volume must be positive, got {volume}")
    
    # Calculate density
    density = mass / volume
    
    return density


if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Normal case with default values from workflow spec
        result1 = calculate_density(mass=50.0, volume=10.0)
        assert result1 == 5.0, f"Expected 5.0, got {result1}"
        print(f"  ✓ calculate_density(50.0, 10.0): {result1} kg/m³")
        
        # Test 2: Integer inputs (should work due to numeric type acceptance)
        result2 = calculate_density(mass=100, volume=20)
        assert result2 == 5.0, f"Expected 5.0, got {result2}"
        print(f"  ✓ calculate_density(100, 20): {result2} kg/m³")
        
        # Test 3: Zero mass (valid edge case)
        result3 = calculate_density(mass=0.0, volume=5.0)
        assert result3 == 0.0, f"Expected 0.0, got {result3}"
        print(f"  ✓ calculate_density(0.0, 5.0): {result3} kg/m³")
        
        # Test 4: Small values
        result4 = calculate_density(mass=0.001, volume=0.0001)
        assert abs(result4 - 10.0) < 1e-9, f"Expected 10.0, got {result4}"
        print(f"  ✓ calculate_density(0.001, 0.0001): {result4} kg/m³")
        
        # Test 5: Large values
        result5 = calculate_density(mass=1e6, volume=1e3)
        assert result5 == 1000.0, f"Expected 1000.0, got {result5}"
        print(f"  ✓ calculate_density(1e6, 1e3): {result5} kg/m³")
        
        # Test 6: Error case - negative mass
        try:
            calculate_density(mass=-10.0, volume=5.0)
            assert False, "Should have raised ValueError for negative mass"
        except ValueError as e:
            assert "non-negative" in str(e), f"Wrong error message: {e}"
            print(f"  ✓ calculate_density(-10.0, 5.0): Correctly raised ValueError")
        
        # Test 7: Error case - zero volume
        try:
            calculate_density(mass=10.0, volume=0.0)
            assert False, "Should have raised ValueError for zero volume"
        except ValueError as e:
            assert "positive" in str(e), f"Wrong error message: {e}"
            print(f"  ✓ calculate_density(10.0, 0.0): Correctly raised ValueError")
        
        # Test 8: Error case - negative volume
        try:
            calculate_density(mass=10.0, volume=-5.0)
            assert False, "Should have raised ValueError for negative volume"
        except ValueError as e:
            assert "positive" in str(e), f"Wrong error message: {e}"
            print(f"  ✓ calculate_density(10.0, -5.0): Correctly raised ValueError")
        
        # Test 9: Error case - invalid type for mass
        try:
            calculate_density(mass="50", volume=10.0)
            assert False, "Should have raised TypeError for string mass"
        except TypeError as e:
            assert "mass must be a number" in str(e), f"Wrong error message: {e}"
            print(f"  ✓ calculate_density('50', 10.0): Correctly raised TypeError")
        
        # Test 10: Error case - invalid type for volume
        try:
            calculate_density(mass=50.0, volume=None)
            assert False, "Should have raised TypeError for None volume"
        except TypeError as e:
            assert "volume must be a number" in str(e), f"Wrong error message: {e}"
            print(f"  ✓ calculate_density(50.0, None): Correctly raised TypeError")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
