"""Activity implementations for line item recognition (LIR).

Generated by CompiledAI Workflow Factory.
"""

from typing import Any, Optional
import re


def _fix_ocr_digits(text: str) -> str:
    """Fix common OCR digit misreadings."""
    replacements = {
        'O': '0', 'o': '0', 'l': '1', 'I': '1',
        'S': '5', 'B': '8', 'Z': '2',
    }
    result = text
    for old, new in replacements.items():
        result = result.replace(old, new)
    return result


def _parse_amount(text: str) -> Optional[float]:
    """Parse a monetary amount from text with OCR error correction."""
    if not text:
        return None
    
    cleaned = re.sub(r'[\$€£¥₹\s]', '', text)
    cleaned = _fix_ocr_digits(cleaned)
    
    # Handle European format (1.234,56) vs US format (1,234.56)
    if ',' in cleaned and '.' in cleaned:
        if cleaned.rfind(',') > cleaned.rfind('.'):
            cleaned = cleaned.replace('.', '').replace(',', '.')
        else:
            cleaned = cleaned.replace(',', '')
    elif ',' in cleaned:
        if re.match(r'^[\d.]+,\d{2}$', cleaned):
            cleaned = cleaned.replace(',', '.')
        else:
            cleaned = cleaned.replace(',', '')
    
    try:
        return float(cleaned)
    except ValueError:
        return None


def _find_table_section(text: str) -> tuple[int, int]:
    """Find the start and end indices of the line items table section."""
    lines = text.split('\n')
    
    # Look for table header patterns
    header_patterns = [
        r'description.*qty.*price',
        r'item.*quantity.*amount',
        r'product.*qty.*total',
        r'service.*hours.*rate',
        r'particulars.*qty.*rate',
        r'description.*units.*price',
    ]
    
    start_idx = 0
    for i, line in enumerate(lines):
        line_lower = line.lower()
        for pattern in header_patterns:
            if re.search(pattern, line_lower):
                start_idx = i + 1
                break
        if start_idx > 0:
            break
    
    # Find end - look for totals section
    end_patterns = ['subtotal', 'sub total', 'total', 'grand total', 'amount due', 'tax', 'vat']
    end_idx = len(lines)
    
    for i in range(start_idx, len(lines)):
        line_lower = lines[i].lower().strip()
        if any(pattern in line_lower for pattern in end_patterns):
            end_idx = i
            break
    
    return start_idx, end_idx


def _parse_line_item(line: str) -> Optional[dict[str, Any]]:
    """Parse a single line item from text."""
    if not line or not line.strip():
        return None
    
    line = line.strip()
    
    # Skip lines that look like headers or totals
    skip_patterns = ['description', 'quantity', 'subtotal', 'total', 'tax', 'vat', '---', '===']
    if any(p in line.lower() for p in skip_patterns):
        return None
    
    # Pattern 1: Description followed by numbers (qty, unit_price, total)
    # E.g., "Widget A    10    $25.00    $250.00"
    pattern1 = r'^(.+?)\s{2,}(\d+(?:\.\d+)?)\s+[\$€£]?([\d,\.]+)\s+[\$€£]?([\d,\.]+)$'
    match = re.match(pattern1, line)
    if match:
        desc, qty, unit_price, total = match.groups()
        return {
            'description': desc.strip(),
            'quantity': float(qty),
            'unit_price': _parse_amount(unit_price),
            'total_price': _parse_amount(total),
        }
    
    # Pattern 2: Simpler format with just description and total
    # E.g., "Consulting Services    $500.00"
    pattern2 = r'^(.+?)\s{2,}[\$€£]?([\d,\.]+)$'
    match = re.match(pattern2, line)
    if match:
        desc, total = match.groups()
        parsed_total = _parse_amount(total)
        if parsed_total and parsed_total > 0:
            return {
                'description': desc.strip(),
                'quantity': 1.0,
                'unit_price': parsed_total,
                'total_price': parsed_total,
            }
    
    # Pattern 3: Tab/pipe separated
    # E.g., "Widget A | 10 | $25.00 | $250.00"
    if '\t' in line or '|' in line:
        parts = re.split(r'[\t|]+', line)
        parts = [p.strip() for p in parts if p.strip()]
        
        if len(parts) >= 2:
            desc = parts[0]
            numbers = []
            for p in parts[1:]:
                num = _parse_amount(p)
                if num is not None:
                    numbers.append(num)
            
            if len(numbers) >= 1:
                if len(numbers) >= 3:
                    return {
                        'description': desc,
                        'quantity': numbers[0],
                        'unit_price': numbers[1],
                        'total_price': numbers[2],
                    }
                elif len(numbers) == 2:
                    # Could be qty + total or unit_price + total
                    if numbers[0] < 100 and numbers[0] == int(numbers[0]):
                        return {
                            'description': desc,
                            'quantity': numbers[0],
                            'unit_price': numbers[1] / numbers[0] if numbers[0] > 0 else numbers[1],
                            'total_price': numbers[1],
                        }
                    else:
                        return {
                            'description': desc,
                            'quantity': 1.0,
                            'unit_price': numbers[0],
                            'total_price': numbers[1],
                        }
                else:
                    return {
                        'description': desc,
                        'quantity': 1.0,
                        'unit_price': numbers[0],
                        'total_price': numbers[0],
                    }
    
    # Pattern 4: Extract numbers at end of line
    nums = re.findall(r'[\$€£]?([\d,]+\.?\d*)', line)
    if nums and len(nums) >= 1:
        # Get description (text before first number)
        desc_match = re.match(r'^([^\d\$€£]+)', line)
        if desc_match:
            desc = desc_match.group(1).strip()
            if desc and len(desc) > 2:
                parsed_nums = [_parse_amount(n) for n in nums]
                parsed_nums = [n for n in parsed_nums if n is not None and n > 0]
                
                if len(parsed_nums) >= 3:
                    return {
                        'description': desc,
                        'quantity': parsed_nums[0],
                        'unit_price': parsed_nums[1],
                        'total_price': parsed_nums[2],
                    }
                elif len(parsed_nums) == 2:
                    return {
                        'description': desc,
                        'quantity': parsed_nums[0] if parsed_nums[0] < 100 else 1.0,
                        'unit_price': parsed_nums[1] if parsed_nums[0] < 100 else parsed_nums[0],
                        'total_price': parsed_nums[1],
                    }
                elif len(parsed_nums) == 1 and parsed_nums[0] > 0:
                    return {
                        'description': desc,
                        'quantity': 1.0,
                        'unit_price': parsed_nums[0],
                        'total_price': parsed_nums[0],
                    }
    
    return None


def extract_line_items(ocr_text: str) -> list[dict[str, Any]]:
    """Extract line items from invoice/receipt OCR text.
    
    Parses the OCR text to find and extract line items from the invoice table.
    Handles various table formats and OCR errors.
    
    Args:
        ocr_text: The raw OCR text containing invoice line items.
        
    Returns:
        List of dictionaries, each containing:
        - description: str - Item description
        - quantity: float - Number of items
        - unit_price: float - Price per unit
        - total_price: float - Line total
        
    Raises:
        TypeError: If ocr_text is not a string
        ValueError: If ocr_text is empty
    """
    if not isinstance(ocr_text, str):
        raise TypeError(f"ocr_text must be str, got {type(ocr_text).__name__}")
    
    if not ocr_text or not ocr_text.strip():
        raise ValueError("ocr_text cannot be empty")
    
    lines = ocr_text.split('\n')
    start_idx, end_idx = _find_table_section(ocr_text)
    
    items = []
    
    # Try parsing lines in the identified table section
    for i in range(start_idx, end_idx):
        if i < len(lines):
            item = _parse_line_item(lines[i])
            if item:
                items.append(item)
    
    # If no items found in table section, try all lines
    if not items:
        for line in lines:
            item = _parse_line_item(line)
            if item:
                items.append(item)
    
    return items


# Test block
if __name__ == "__main__":
    import sys
    
    print("Testing LIR activities...")
    
    sample_ocr = """
    Invoice #12345
    
    Description                     Qty    Price     Amount
    Widget A                        10     $25.00    $250.00
    Widget B                         5     $30.00    $150.00
    Consulting Services              2     $100.00   $200.00
    
    Subtotal:                                        $600.00
    Tax (8%):                                         $48.00
    Total:                                           $648.00
    """
    
    try:
        result = extract_line_items(sample_ocr)
        
        assert result is not None, "extract_line_items returned None"
        assert isinstance(result, list), "Result should be a list"
        assert len(result) >= 1, f"Should have at least 1 item, got {len(result)}"
        
        print(f"  ✓ extract_line_items: found {len(result)} items")
        
        for i, item in enumerate(result):
            print(f"    Item {i+1}: {item['description']}")
            print(f"      qty={item['quantity']}, unit={item['unit_price']}, total={item['total_price']}")
            
            assert 'description' in item, "Missing description"
            assert 'quantity' in item, "Missing quantity"
            assert 'unit_price' in item, "Missing unit_price"
            assert 'total_price' in item, "Missing total_price"
        
        # Test error handling
        try:
            extract_line_items(123)
            sys.exit(1)
        except TypeError:
            print("  ✓ TypeError correctly raised for non-string")
        
        try:
            extract_line_items("")
            sys.exit(1)
        except ValueError:
            print("  ✓ ValueError correctly raised for empty string")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        import traceback
        traceback.print_exc()
        sys.exit(1)
