"""Activity implementations for cosine_similarity_calculation.

Generated by CompiledAI Workflow Factory.
"""

from typing import List
import math


def calculate_cosine_similarity(vectorA: List[float], vectorB: List[float]) -> float:
    """Calculate the cosine similarity between two vectors.
    
    Computes the dot product divided by the product of their magnitudes.
    Cosine similarity measures the cosine of the angle between two vectors,
    providing a similarity score between -1 and 1.
    
    Args:
        vectorA: The first vector of float values
        vectorB: The second vector of float values
        
    Returns:
        The cosine similarity score between the two vectors, ranging from -1 to 1
        
    Raises:
        TypeError: If inputs are not lists or contain non-numeric values
        ValueError: If vectors are empty, have different lengths, or have zero magnitude
    """
    # Input validation - check types
    if not isinstance(vectorA, list):
        raise TypeError(f"vectorA must be a list, got {type(vectorA).__name__}")
    if not isinstance(vectorB, list):
        raise TypeError(f"vectorB must be a list, got {type(vectorB).__name__}")
    
    # Check for empty vectors
    if len(vectorA) == 0:
        raise ValueError("vectorA cannot be empty")
    if len(vectorB) == 0:
        raise ValueError("vectorB cannot be empty")
    
    # Check for equal lengths
    if len(vectorA) != len(vectorB):
        raise ValueError(
            f"Vectors must have the same length, got {len(vectorA)} and {len(vectorB)}"
        )
    
    # Validate all elements are numeric
    for i, val in enumerate(vectorA):
        if not isinstance(val, (int, float)):
            raise TypeError(
                f"vectorA[{i}] must be a number, got {type(val).__name__}"
            )
    for i, val in enumerate(vectorB):
        if not isinstance(val, (int, float)):
            raise TypeError(
                f"vectorB[{i}] must be a number, got {type(val).__name__}"
            )
    
    # Calculate dot product
    dot_product = sum(a * b for a, b in zip(vectorA, vectorB))
    
    # Calculate magnitudes
    magnitude_a = math.sqrt(sum(a * a for a in vectorA))
    magnitude_b = math.sqrt(sum(b * b for b in vectorB))
    
    # Check for zero magnitude vectors
    if magnitude_a == 0:
        raise ValueError("vectorA has zero magnitude (all zeros)")
    if magnitude_b == 0:
        raise ValueError("vectorB has zero magnitude (all zeros)")
    
    # Calculate cosine similarity
    similarity = dot_product / (magnitude_a * magnitude_b)
    
    # Clamp result to [-1, 1] to handle floating point errors
    return max(-1.0, min(1.0, similarity))


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Normal case with default values from workflow
        vector_a = [0.3, 0.8, 0.1, 0.6, 0.2]
        vector_b = [0.5, 0.7, 0.4, 0.9, 0.3]
        result = calculate_cosine_similarity(vector_a, vector_b)
        assert -1 <= result <= 1, f"Result {result} out of range [-1, 1]"
        print(f"  ✓ calculate_cosine_similarity (default vectors): {result:.6f}")
        
        # Test 2: Identical vectors should give 1.0
        identical = [1.0, 2.0, 3.0]
        result_identical = calculate_cosine_similarity(identical, identical)
        assert abs(result_identical - 1.0) < 1e-9, f"Identical vectors should give 1.0, got {result_identical}"
        print(f"  ✓ calculate_cosine_similarity (identical vectors): {result_identical}")
        
        # Test 3: Opposite vectors should give -1.0
        vec_pos = [1.0, 0.0, 0.0]
        vec_neg = [-1.0, 0.0, 0.0]
        result_opposite = calculate_cosine_similarity(vec_pos, vec_neg)
        assert abs(result_opposite - (-1.0)) < 1e-9, f"Opposite vectors should give -1.0, got {result_opposite}"
        print(f"  ✓ calculate_cosine_similarity (opposite vectors): {result_opposite}")
        
        # Test 4: Orthogonal vectors should give 0.0
        vec_x = [1.0, 0.0, 0.0]
        vec_y = [0.0, 1.0, 0.0]
        result_orthogonal = calculate_cosine_similarity(vec_x, vec_y)
        assert abs(result_orthogonal) < 1e-9, f"Orthogonal vectors should give 0.0, got {result_orthogonal}"
        print(f"  ✓ calculate_cosine_similarity (orthogonal vectors): {result_orthogonal}")
        
        # Test 5: Type error for non-list input
        try:
            calculate_cosine_similarity("not a list", [1, 2, 3])
            assert False, "Should have raised TypeError"
        except TypeError as e:
            assert "vectorA must be a list" in str(e)
            print(f"  ✓ calculate_cosine_similarity (type error vectorA): caught correctly")
        
        # Test 6: Empty vector error
        try:
            calculate_cosine_similarity([], [1, 2, 3])
            assert False, "Should have raised ValueError"
        except ValueError as e:
            assert "cannot be empty" in str(e)
            print(f"  ✓ calculate_cosine_similarity (empty vector): caught correctly")
        
        # Test 7: Mismatched lengths error
        try:
            calculate_cosine_similarity([1, 2], [1, 2, 3])
            assert False, "Should have raised ValueError"
        except ValueError as e:
            assert "same length" in str(e)
            print(f"  ✓ calculate_cosine_similarity (mismatched lengths): caught correctly")
        
        # Test 8: Zero magnitude error
        try:
            calculate_cosine_similarity([0, 0, 0], [1, 2, 3])
            assert False, "Should have raised ValueError"
        except ValueError as e:
            assert "zero magnitude" in str(e)
            print(f"  ✓ calculate_cosine_similarity (zero magnitude): caught correctly")
        
        # Test 9: Non-numeric element error
        try:
            calculate_cosine_similarity([1, "two", 3], [1, 2, 3])
            assert False, "Should have raised TypeError"
        except TypeError as e:
            assert "must be a number" in str(e)
            print(f"  ✓ calculate_cosine_similarity (non-numeric element): caught correctly")
        
        # Test 10: Integer inputs work correctly
        int_vec_a = [1, 2, 3]
        int_vec_b = [4, 5, 6]
        result_int = calculate_cosine_similarity(int_vec_a, int_vec_b)
        expected = (1*4 + 2*5 + 3*6) / (math.sqrt(14) * math.sqrt(77))
        assert abs(result_int - expected) < 1e-9, f"Integer vector test failed: {result_int} != {expected}"
        print(f"  ✓ calculate_cosine_similarity (integer vectors): {result_int:.6f}")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
