"""Dynamic loading of generated activity code as executable functions."""

from typing import Dict, Callable, Any, Awaitable
import ast
import inspect
import logging

logger = logging.getLogger(__name__)


class DynamicLoadError(Exception):
    """Raised when dynamic code loading fails."""

    pass


class DynamicModuleLoader:
    """
    Load generated activity code as executable async functions.

    This loader converts Python code strings (generated by CodeFactory)
    into executable functions that can be called by the workflow executor.

    Security Note:
        - Code comes from validated CodeFactory output
        - YAML has been validated by DSL validator
        - Namespace isolation prevents global state pollution
        - Not a sandbox - assumes generated code is trusted

    Example:
        >>> loader = DynamicModuleLoader()
        >>> activities_code = '''
        ... async def classify_text(text: str) -> dict:
        ...     return {"category": "spam"}
        ... '''
        >>> functions = loader.load(activities_code, "workflow_001")
        >>> result = await functions["classify_text"]("test")
        >>> print(result)  # {"category": "spam"}
    """

    @staticmethod
    def create_namespace(workflow_id: str, llm_client: Any = None) -> Dict[str, Any]:
        """
        Create isolated namespace for code execution.

        Provides access to standard library and common packages
        that are installed in the project (numpy, pandas, httpx, etc.).

        Args:
            workflow_id: Unique workflow identifier (for debugging)
            llm_client: Optional LLM client instance to inject for activities

        Returns:
            Namespace dictionary with imports and builtins

        Example:
            >>> ns = DynamicModuleLoader.create_namespace("wf_001")
            >>> 'asyncio' in ns
            True
            >>> 'numpy' in ns  # If installed
            True
        """
        # Base namespace
        namespace = {
            "__name__": f"generated_workflow_{workflow_id}",
            "__builtins__": __builtins__,
        }

        # Inject LLM client if provided
        if llm_client is not None:
            namespace["llm_client"] = llm_client

        # Standard library modules
        stdlib_modules = [
            "asyncio", "json", "datetime", "pathlib", "re",
            "math", "random", "collections", "itertools", "functools"
        ]
        for module_name in stdlib_modules:
            try:
                namespace[module_name] = __import__(module_name)
            except ImportError:
                pass

        # Type hints
        namespace.update({
            "Any": Any,
            "Dict": Dict,
            "List": list,
            "Optional": type(None),
        })

        # Third-party packages (with common aliases)
        thirdparty_packages = [
            ("numpy", "np"),
            ("pandas", "pd"),
            ("httpx", None),
            ("pydantic", None),
            ("yaml", None),
            ("jsonschema", None),
        ]

        for package_name, alias in thirdparty_packages:
            try:
                module = __import__(package_name)
                namespace[package_name] = module
                if alias:
                    namespace[alias] = module
            except ImportError:
                logger.debug(f"Package {package_name} not available")

        return namespace

    @staticmethod
    def validate_code(code: str) -> None:
        """
        Validate Python code syntax without executing.

        Uses ast.parse() to check for syntax errors before exec().
        This catches errors early with clearer error messages.

        Args:
            code: Python code string to validate

        Raises:
            DynamicLoadError: If code has syntax errors

        Example:
            >>> DynamicModuleLoader.validate_code("def foo(): return 42")
            >>> # No exception - code is valid
            >>> DynamicModuleLoader.validate_code("def foo(: invalid")
            Traceback (most recent call last):
                ...
            DynamicLoadError: Syntax error in generated code: ...
        """
        try:
            ast.parse(code)
        except SyntaxError as e:
            raise DynamicLoadError(f"Syntax error in generated code: {e}") from e

    @staticmethod
    def extract_async_functions(namespace: Dict[str, Any]) -> Dict[str, Callable]:
        """
        Extract async functions from executed namespace.

        Scans namespace for coroutine functions (async def) and extracts
        them as activities. Regular functions are ignored since workflow
        activities must be async.

        Args:
            namespace: Namespace after exec() has been called

        Returns:
            Dictionary mapping function names to async callables

        Example:
            >>> ns = {'foo': lambda: None, '__builtins__': __builtins__}
            >>> # After exec() with async def bar(): ...
            >>> functions = DynamicModuleLoader.extract_async_functions(ns)
            >>> 'bar' in functions
            True
        """
        functions = {}

        for name, obj in namespace.items():
            # Skip private/magic methods and non-functions
            if name.startswith("_"):
                continue

            # Only extract async functions (activities must be async)
            if inspect.iscoroutinefunction(obj):
                functions[name] = obj
                logger.debug(f"Loaded activity: {name}")

        return functions

    def load(
        self, activities_code: str, workflow_id: str, llm_client: Any = None
    ) -> Dict[str, Callable[..., Awaitable[Any]]]:
        """
        Load generated activities code as executable functions.

        Process:
        1. Validate syntax with ast.parse()
        2. Create isolated namespace with required imports
        3. Execute code in namespace via exec()
        4. Extract async functions from namespace
        5. Return mapping of activity names to callables

        Args:
            activities_code: Generated Python code string from CodeFactory
            workflow_id: Workflow identifier (for debugging and namespace)
            llm_client: Optional LLM client instance to inject for activities

        Returns:
            Dictionary mapping activity names to async callable functions

        Raises:
            DynamicLoadError: If code is empty, has syntax errors,
                fails to execute, or contains no async functions

        Example:
            >>> loader = DynamicModuleLoader()
            >>> code = '''
            ... async def process_data(data: str) -> dict:
            ...     return {"processed": data.upper()}
            ... '''
            >>> activities = loader.load(code, "workflow_123")
            >>> len(activities)
            1
            >>> 'process_data' in activities
            True
        """
        if not activities_code or not activities_code.strip():
            raise DynamicLoadError("Empty activities code provided")

        # Step 1: Validate syntax
        self.validate_code(activities_code)

        # Step 2: Create namespace with LLM client
        namespace = self.create_namespace(workflow_id, llm_client=llm_client)

        # Step 3: Execute code
        try:
            exec(activities_code, namespace)
        except ModuleNotFoundError as e:
            # Provide helpful error message for missing imports
            missing_module = str(e).split("'")[1] if "'" in str(e) else "unknown"
            raise DynamicLoadError(
                f"Generated code requires module '{missing_module}' which is not available. "
                f"Generated activities should only use standard library modules or modules "
                f"available in the namespace. Error: {e}"
            ) from e
        except Exception as e:
            raise DynamicLoadError(
                f"Failed to execute generated code: {e}"
            ) from e

        # Step 4: Extract functions
        functions = self.extract_async_functions(namespace)

        if not functions:
            raise DynamicLoadError(
                "No async functions found in generated code. "
                "All activities must be async functions."
            )

        # Step 5: Log loaded activities
        logger.info(
            f"Loaded {len(functions)} activities from workflow {workflow_id}: "
            f"{list(functions.keys())}"
        )

        return functions
