"""Activity implementations for basketball_free_throw_probability.

Generated by CompiledAI Workflow Factory.
"""

from typing import Any
import math


def calc_binomial_probability(n: int, k: int, p: float) -> float:
    """Calculate the probability of getting exactly k successes in n trials.
    
    Uses the binomial probability formula: P(X=k) = C(n,k) * p^k * (1-p)^(n-k)
    where C(n,k) is the binomial coefficient "n choose k".
    
    Args:
        n: The number of trials (total free throw attempts). Must be non-negative.
        k: The number of successes (free throws made). Must be between 0 and n.
        p: The probability of success on each trial. Must be between 0 and 1.
        
    Returns:
        The probability of getting exactly k successes in n trials.
        
    Raises:
        TypeError: If n or k is not an integer, or p is not a number.
        ValueError: If n < 0, k < 0, k > n, or p is not in [0, 1].
    """
    # Type validation
    if not isinstance(n, int):
        raise TypeError(f"n must be int, got {type(n).__name__}")
    if not isinstance(k, int):
        raise TypeError(f"k must be int, got {type(k).__name__}")
    if not isinstance(p, (int, float)):
        raise TypeError(f"p must be a number, got {type(p).__name__}")
    
    # Value validation
    if n < 0:
        raise ValueError(f"n must be non-negative, got {n}")
    if k < 0:
        raise ValueError(f"k must be non-negative, got {k}")
    if k > n:
        raise ValueError(f"k must not exceed n, got k={k} > n={n}")
    if not (0 <= p <= 1):
        raise ValueError(f"p must be between 0 and 1, got {p}")
    
    # Edge cases
    if p == 0:
        return 1.0 if k == 0 else 0.0
    if p == 1:
        return 1.0 if k == n else 0.0
    
    # Binomial coefficient C(n, k) = n! / (k! * (n-k)!)
    binomial_coeff = math.comb(n, k)
    
    # Binomial probability formula: P(X=k) = C(n,k) * p^k * (1-p)^(n-k)
    probability = binomial_coeff * (p ** k) * ((1 - p) ** (n - k))
    
    return probability


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Default values from workflow spec
        result1 = calc_binomial_probability(n=30, k=15, p=0.5)
        expected1 = math.comb(30, 15) * (0.5 ** 15) * (0.5 ** 15)
        assert abs(result1 - expected1) < 1e-10, f"Expected {expected1}, got {result1}"
        print(f"  ✓ calc_binomial_probability(30, 15, 0.5): {result1:.6f}")
        
        # Test 2: Simple case - 1 attempt, 1 success, 100% probability
        result2 = calc_binomial_probability(n=1, k=1, p=1.0)
        assert result2 == 1.0, f"Expected 1.0, got {result2}"
        print(f"  ✓ calc_binomial_probability(1, 1, 1.0): {result2}")
        
        # Test 3: Zero successes with low probability
        result3 = calc_binomial_probability(n=5, k=0, p=0.1)
        expected3 = (0.9 ** 5)
        assert abs(result3 - expected3) < 1e-10, f"Expected {expected3}, got {result3}"
        print(f"  ✓ calc_binomial_probability(5, 0, 0.1): {result3:.6f}")
        
        # Test 4: All successes
        result4 = calc_binomial_probability(n=3, k=3, p=0.8)
        expected4 = 0.8 ** 3
        assert abs(result4 - expected4) < 1e-10, f"Expected {expected4}, got {result4}"
        print(f"  ✓ calc_binomial_probability(3, 3, 0.8): {result4:.6f}")
        
        # Test 5: Edge case p=0
        result5 = calc_binomial_probability(n=10, k=0, p=0.0)
        assert result5 == 1.0, f"Expected 1.0, got {result5}"
        print(f"  ✓ calc_binomial_probability(10, 0, 0.0): {result5}")
        
        # Test 6: Edge case p=0 with k>0
        result6 = calc_binomial_probability(n=10, k=5, p=0.0)
        assert result6 == 0.0, f"Expected 0.0, got {result6}"
        print(f"  ✓ calc_binomial_probability(10, 5, 0.0): {result6}")
        
        # Test 7: Edge case n=0, k=0
        result7 = calc_binomial_probability(n=0, k=0, p=0.5)
        assert result7 == 1.0, f"Expected 1.0, got {result7}"
        print(f"  ✓ calc_binomial_probability(0, 0, 0.5): {result7}")
        
        # Test 8: Error case - invalid type for n
        try:
            calc_binomial_probability(n=3.5, k=2, p=0.5)
            assert False, "Should have raised TypeError"
        except TypeError as e:
            print(f"  ✓ TypeError for non-int n: {e}")
        
        # Test 9: Error case - k > n
        try:
            calc_binomial_probability(n=5, k=10, p=0.5)
            assert False, "Should have raised ValueError"
        except ValueError as e:
            print(f"  ✓ ValueError for k > n: {e}")
        
        # Test 10: Error case - p out of range
        try:
            calc_binomial_probability(n=5, k=2, p=1.5)
            assert False, "Should have raised ValueError"
        except ValueError as e:
            print(f"  ✓ ValueError for p > 1: {e}")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
