"""Activity implementations for binomial_probability_calculation.

Generated by CompiledAI Workflow Factory.
"""

from typing import Any
import math


def calc_binomial_probability(n: int, k: int, p: float) -> float:
    """Calculate the probability of getting exactly k successes in n trials.
    
    Uses the binomial distribution formula:
    P(X = k) = C(n, k) * p^k * (1-p)^(n-k)
    
    Args:
        n: The number of trials (total rounds played)
        k: The number of successes (wins) desired
        p: The probability of success on each trial (win probability per round)
        
    Returns:
        The probability of getting exactly k successes in n trials
        
    Raises:
        TypeError: If n or k is not an integer, or p is not a float/int
        ValueError: If n < 0, k < 0, k > n, or p is not between 0 and 1
    """
    # Input validation - type checks
    if not isinstance(n, int):
        raise TypeError(f"n must be int, got {type(n).__name__}")
    if not isinstance(k, int):
        raise TypeError(f"k must be int, got {type(k).__name__}")
    if not isinstance(p, (int, float)):
        raise TypeError(f"p must be float or int, got {type(p).__name__}")
    
    # Input validation - value checks
    if n < 0:
        raise ValueError(f"n must be non-negative, got {n}")
    if k < 0:
        raise ValueError(f"k must be non-negative, got {k}")
    if k > n:
        raise ValueError(f"k cannot exceed n, got k={k}, n={n}")
    if not (0 <= p <= 1):
        raise ValueError(f"p must be between 0 and 1, got {p}")
    
    # Calculate binomial coefficient C(n, k) = n! / (k! * (n-k)!)
    binomial_coeff = math.comb(n, k)
    
    # Calculate probability: C(n,k) * p^k * (1-p)^(n-k)
    probability = binomial_coeff * (p ** k) * ((1 - p) ** (n - k))
    
    return probability


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test calc_binomial_probability with basic case
        result1 = calc_binomial_probability(n=10, k=3, p=0.3)
        expected1 = 0.2668  # Approximate expected value
        assert abs(result1 - expected1) < 0.001, f"Expected ~{expected1}, got {result1}"
        print(f"  ✓ calc_binomial_probability(10, 3, 0.3): {result1:.6f}")
        
        # Test with scenario from workflow: n=15, k=5, p=0.3
        result2 = calc_binomial_probability(n=15, k=5, p=0.3)
        expected2 = 0.2061  # Approximate expected value
        assert abs(result2 - expected2) < 0.001, f"Expected ~{expected2}, got {result2}"
        print(f"  ✓ calc_binomial_probability(15, 5, 0.3): {result2:.6f}")
        
        # Test with scenario from workflow: n=20, k=7, p=0.3
        result3 = calc_binomial_probability(n=20, k=7, p=0.3)
        expected3 = 0.1643  # Approximate expected value
        assert abs(result3 - expected3) < 0.001, f"Expected ~{expected3}, got {result3}"
        print(f"  ✓ calc_binomial_probability(20, 7, 0.3): {result3:.6f}")
        
        # Test edge case: k=0 (no successes)
        result4 = calc_binomial_probability(n=5, k=0, p=0.5)
        expected4 = 0.03125  # (0.5)^5
        assert abs(result4 - expected4) < 0.0001, f"Expected {expected4}, got {result4}"
        print(f"  ✓ calc_binomial_probability(5, 0, 0.5): {result4:.6f}")
        
        # Test edge case: k=n (all successes)
        result5 = calc_binomial_probability(n=5, k=5, p=0.5)
        expected5 = 0.03125  # (0.5)^5
        assert abs(result5 - expected5) < 0.0001, f"Expected {expected5}, got {result5}"
        print(f"  ✓ calc_binomial_probability(5, 5, 0.5): {result5:.6f}")
        
        # Test edge case: p=0 (impossible success)
        result6 = calc_binomial_probability(n=10, k=0, p=0.0)
        assert result6 == 1.0, f"Expected 1.0, got {result6}"
        print(f"  ✓ calc_binomial_probability(10, 0, 0.0): {result6:.6f}")
        
        # Test edge case: p=1 (guaranteed success)
        result7 = calc_binomial_probability(n=10, k=10, p=1.0)
        assert result7 == 1.0, f"Expected 1.0, got {result7}"
        print(f"  ✓ calc_binomial_probability(10, 10, 1.0): {result7:.6f}")
        
        # Test error handling: invalid types
        try:
            calc_binomial_probability(n=10.5, k=3, p=0.3)
            assert False, "Should have raised TypeError for float n"
        except TypeError as e:
            print(f"  ✓ TypeError raised for float n: {e}")
        
        # Test error handling: k > n
        try:
            calc_binomial_probability(n=5, k=10, p=0.3)
            assert False, "Should have raised ValueError for k > n"
        except ValueError as e:
            print(f"  ✓ ValueError raised for k > n: {e}")
        
        # Test error handling: p out of range
        try:
            calc_binomial_probability(n=10, k=3, p=1.5)
            assert False, "Should have raised ValueError for p > 1"
        except ValueError as e:
            print(f"  ✓ ValueError raised for p > 1: {e}")
        
        # Test error handling: negative n
        try:
            calc_binomial_probability(n=-5, k=3, p=0.3)
            assert False, "Should have raised ValueError for negative n"
        except ValueError as e:
            print(f"  ✓ ValueError raised for negative n: {e}")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
