"""Activity implementations for invoice_ocr_extraction.

Generated by CompiledAI Workflow Factory.
"""

from typing import Any, Optional
import re
from datetime import datetime


def _fix_ocr_digits(text: str) -> str:
    """Fix common OCR digit misreadings.
    
    Args:
        text: Text containing potential OCR errors
        
    Returns:
        Text with common digit substitutions corrected
    """
    # Common OCR substitutions for digits
    replacements = {
        'O': '0',
        'o': '0',
        'l': '1',
        'I': '1',
        'i': '1',
        'S': '5',
        'B': '8',
        'Z': '2',
    }
    result = text
    for old, new in replacements.items():
        result = result.replace(old, new)
    return result


def _parse_amount(text: str) -> Optional[float]:
    """Parse a monetary amount from text with OCR error correction.
    
    Args:
        text: Text containing a monetary amount
        
    Returns:
        Parsed float amount or None if parsing fails
    """
    if not text:
        return None
    
    # Remove currency symbols and whitespace
    cleaned = re.sub(r'[\$€£¥₹\s,]', '', text)
    
    # Fix OCR digit errors
    cleaned = _fix_ocr_digits(cleaned)
    
    # Handle European format (1.234,56) vs US format (1,234.56)
    if ',' in cleaned and '.' in cleaned:
        if cleaned.rfind(',') > cleaned.rfind('.'):
            # European format: 1.234,56
            cleaned = cleaned.replace('.', '').replace(',', '.')
        else:
            # US format: 1,234.56
            cleaned = cleaned.replace(',', '')
    elif ',' in cleaned:
        # Could be European decimal separator or US thousands separator
        # If there are exactly 2 digits after comma, treat as decimal
        if re.match(r'^[\d.]+,\d{2}$', cleaned):
            cleaned = cleaned.replace(',', '.')
        else:
            cleaned = cleaned.replace(',', '')
    
    try:
        return float(cleaned)
    except ValueError:
        return None


def _normalize_date(date_str: str) -> Optional[str]:
    """Normalize a date string to ISO format (YYYY-MM-DD).
    
    Args:
        date_str: Date string in various formats
        
    Returns:
        ISO formatted date string or original if unparseable
    """
    if not date_str:
        return None
    
    date_str = date_str.strip()
    
    # Fix common OCR errors in dates
    date_str = _fix_ocr_digits(date_str)
    
    # Common date formats to try
    formats = [
        '%Y-%m-%d',      # 2024-01-15
        '%d-%m-%Y',      # 15-01-2024
        '%m-%d-%Y',      # 01-15-2024
        '%Y/%m/%d',      # 2024/01/15
        '%d/%m/%Y',      # 15/01/2024
        '%m/%d/%Y',      # 01/15/2024
        '%d.%m.%Y',      # 15.01.2024
        '%B %d, %Y',     # January 15, 2024
        '%b %d, %Y',     # Jan 15, 2024
        '%d %B %Y',      # 15 January 2024
        '%d %b %Y',      # 15 Jan 2024
    ]
    
    for fmt in formats:
        try:
            parsed = datetime.strptime(date_str, fmt)
            return parsed.strftime('%Y-%m-%d')
        except ValueError:
            continue
    
    # Return original if no format matched
    return date_str


def _extract_document_id(text: str) -> Optional[str]:
    """Extract invoice/receipt number from text.
    
    Args:
        text: OCR text to search
        
    Returns:
        Document ID or None
    """
    # Common patterns for invoice numbers - more specific patterns first
    patterns = [
        # Patterns with explicit "No.", "Number", "#" markers
        r'(?:Invoice|Receipt|Order)\s*(?:No\.?|Number|#)[\s:]*([A-Z0-9][-A-Z0-9]+)',
        # INV-12345, REC-12345 format
        r'(?:INV|REC|ORD)[-#]([A-Z0-9][-A-Z0-9]+)',
        # Invoice #12345 or Invoice: 12345
        r'(?:Invoice|Receipt|Order)[\s#:]+([A-Z0-9][-A-Z0-9]{3,})',
        # Standalone # followed by ID
        r'#\s*([A-Z0-9][-A-Z0-9]{4,})',
        # Document/Doc pattern
        r'(?:Document|Doc)[\s#:.-]*([A-Z0-9][-A-Z0-9]+)',
    ]
    
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            result = match.group(1).strip()
            # Filter out false positives like "No" alone
            if len(result) >= 3 and not result.upper() in ('NO', 'NO.'):
                return result
    
    return None


def _extract_vendor_name(text: str) -> Optional[str]:
    """Extract vendor/seller name from text.
    
    Args:
        text: OCR text to search
        
    Returns:
        Vendor name or None
    """
    lines = text.strip().split('\n')
    
    # Often the vendor name is at the very top of the invoice
    # Look for common patterns first
    patterns = [
        r'(?:From|Seller|Vendor|Company|Sold\s*by)[\s:]+([^\n]+)',
        r'(?:Bill\s*From)[\s:]+([^\n]+)',
    ]
    
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            name = match.group(1).strip()
            if name:
                return name
    
    # Fallback: First non-empty line that looks like a company name
    for line in lines[:5]:  # Check first 5 lines
        line = line.strip()
        if line and len(line) > 2 and not re.match(r'^[\d\W]+$', line):
            # Skip lines that look like dates, amounts, or addresses
            if not re.search(r'\d{1,2}[/.-]\d{1,2}[/.-]\d{2,4}', line):
                if not re.search(r'^\$|^€|^£|^\d+\.\d{2}$', line):
                    return line
    
    return None


def _extract_address(text: str, marker: str) -> Optional[str]:
    """Extract an address block following a marker.
    
    Args:
        text: OCR text to search
        marker: The label before the address (e.g., "Bill To", "Ship To")
        
    Returns:
        Address string or None
    """
    pattern = rf'{marker}[\s:]*\n?((?:[^\n]+\n?){{1,5}})'
    match = re.search(pattern, text, re.IGNORECASE)
    
    if match:
        address_block = match.group(1).strip()
        # Clean up the address - remove empty lines and limit length
        lines = [l.strip() for l in address_block.split('\n') if l.strip()]
        
        # Stop at common section breaks
        clean_lines = []
        stop_words = ['invoice', 'date', 'total', 'amount', 'due', 'payment', 'item', 'description', 'qty']
        for line in lines:
            if any(word in line.lower() for word in stop_words):
                break
            clean_lines.append(line)
        
        if clean_lines:
            return '\n'.join(clean_lines)
    
    return None


def _extract_customer_name(text: str) -> Optional[str]:
    """Extract customer/buyer name from text.
    
    Args:
        text: OCR text to search
        
    Returns:
        Customer name or None
    """
    patterns = [
        r'(?:Bill\s*To|Customer|Client|Buyer|Sold\s*To|Ship\s*To)[\s:]+([^\n]+)',
    ]
    
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            name = match.group(1).strip()
            # Clean up - remove things that look like addresses
            if name and not re.search(r'\d{5}', name):  # Skip if looks like has zip code
                return name.split('\n')[0]  # First line only
    
    return None


def _extract_date(text: str, keywords: list[str]) -> Optional[str]:
    """Extract a date associated with specific keywords.
    
    Args:
        text: OCR text to search
        keywords: List of keywords to look for before the date
        
    Returns:
        Normalized date string or None
    """
    for keyword in keywords:
        pattern = rf'{keyword}[\s:]*([^\n]+)'
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            date_str = match.group(1).strip()
            # Extract just the date part
            date_match = re.search(
                r'(\d{1,4}[-/\.]\d{1,2}[-/\.]\d{1,4}|\w+\s+\d{1,2},?\s+\d{4}|\d{1,2}\s+\w+\s+\d{4})',
                date_str
            )
            if date_match:
                return _normalize_date(date_match.group(1))
    
    return None


def _extract_amount(text: str, keywords: list[str]) -> Optional[float]:
    """Extract a monetary amount associated with specific keywords.
    
    Args:
        text: OCR text to search
        keywords: List of keywords to look for before the amount
        
    Returns:
        Parsed float amount or None
    """
    for keyword in keywords:
        # Use word boundary to avoid matching "Subtotal" when looking for "Total"
        # Allow optional content like "(8%)" between keyword and amount
        pattern = rf'(?:^|[\s])({keyword})(?:\s*\([^)]*\))?[\s:]*[\$€£¥₹]?\s*([\d,.\s]+)'
        for match in re.finditer(pattern, text, re.IGNORECASE | re.MULTILINE):
            # Skip if this is part of a compound word (e.g., "Subtotal" when looking for "Total")
            start = match.start(1)
            if start > 0 and text[start-1:start].isalpha():
                continue
            amount = _parse_amount(match.group(2))
            if amount is not None:
                return amount
    
    return None


def _extract_currency(text: str) -> Optional[str]:
    """Extract currency code from text.
    
    Args:
        text: OCR text to search
        
    Returns:
        Three-letter currency code or None
    """
    # Look for explicit currency codes
    code_match = re.search(r'\b(USD|EUR|GBP|CAD|AUD|JPY|CHF|CNY|INR)\b', text, re.IGNORECASE)
    if code_match:
        return code_match.group(1).upper()
    
    # Infer from currency symbols
    if '$' in text:
        # Check for CAD, AUD indicators
        if re.search(r'\b(Canada|Canadian|CAD)\b', text, re.IGNORECASE):
            return 'CAD'
        if re.search(r'\b(Australia|Australian|AUD)\b', text, re.IGNORECASE):
            return 'AUD'
        return 'USD'
    if '€' in text:
        return 'EUR'
    if '£' in text:
        return 'GBP'
    if '¥' in text:
        if re.search(r'\b(Japan|Japanese|JPY)\b', text, re.IGNORECASE):
            return 'JPY'
        return 'CNY'
    if '₹' in text:
        return 'INR'
    
    return None


def extract_invoice_fields(ocr_text: str) -> dict[str, Any]:
    """Parse raw OCR text to extract all invoice/receipt fields.
    
    Uses regex patterns and heuristic string matching to identify key fields.
    Handles common OCR artifacts and variations in invoice formats. Each field
    extraction is attempted independently so partial results are returned even
    if some fields fail.
    
    Args:
        ocr_text: The raw OCR text to parse. May contain noise characters,
            line breaks, inconsistent spacing, and OCR misreadings.
            
    Returns:
        Dictionary containing all extracted fields:
        - document_id: str or None - Invoice/receipt number
        - vendor_name: str or None - Name of the seller/vendor company
        - vendor_address: str or None - Full address of vendor
        - customer_name: str or None - Name of the buyer/customer
        - customer_address: str or None - Full address of customer
        - invoice_date: str or None - Issue date in ISO format or original
        - due_date: str or None - Payment due date in ISO format or original
        - total_amount: float or None - Total amount to pay
        - tax_amount: float or None - Tax/VAT amount if listed
        - currency: str or None - Three-letter currency code
        
    Raises:
        TypeError: If ocr_text is not a string
        ValueError: If ocr_text is empty or contains only whitespace
    """
    # Input validation
    if not isinstance(ocr_text, str):
        raise TypeError(f"ocr_text must be str, got {type(ocr_text).__name__}")
    
    if not ocr_text or not ocr_text.strip():
        raise ValueError("ocr_text cannot be empty or contain only whitespace")
    
    # Initialize result dictionary with all fields as None
    result: dict[str, Any] = {
        'document_id': None,
        'vendor_name': None,
        'vendor_address': None,
        'customer_name': None,
        'customer_address': None,
        'invoice_date': None,
        'due_date': None,
        'total_amount': None,
        'tax_amount': None,
        'currency': None,
    }
    
    # Extract each field independently
    result['document_id'] = _extract_document_id(ocr_text)
    result['vendor_name'] = _extract_vendor_name(ocr_text)
    result['vendor_address'] = _extract_address(ocr_text, r'(?:From|Seller|Vendor|Bill\s*From)')
    result['customer_name'] = _extract_customer_name(ocr_text)
    result['customer_address'] = _extract_address(ocr_text, r'(?:Bill\s*To|Ship\s*To|Customer|Client)')
    
    result['invoice_date'] = _extract_date(
        ocr_text, 
        ['Invoice Date', 'Date of Issue', 'Issue Date', 'Date']
    )
    result['due_date'] = _extract_date(
        ocr_text, 
        ['Due Date', 'Payment Due', 'Pay By', 'Due']
    )
    
    result['total_amount'] = _extract_amount(
        ocr_text, 
        ['Total', 'Grand Total', 'Amount Due', 'Total Amount', 'Total Due', 'Balance Due']
    )
    result['tax_amount'] = _extract_amount(
        ocr_text, 
        ['Tax', 'VAT', 'GST', 'Sales Tax', 'Tax Amount']
    )
    
    result['currency'] = _extract_currency(ocr_text)
    
    return result


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    # Sample OCR text for testing
    sample_ocr = """
    Acme Corporation
    123 Business Lane
    Suite 456
    New York, NY 10001
    
    Invoice #INV-2024-00123
    
    Invoice Date: January 15, 2024
    Due Date: February 15, 2024
    
    Bill To:
    John Smith
    789 Customer Street
    Los Angeles, CA 90001
    
    Description                     Qty    Price     Amount
    Widget A                        10     $25.00    $250.00
    Widget B                         5     $30.00    $150.00
    
    Subtotal:                                        $400.00
    Tax (8%):                                         $32.00
    Total:                                           $432.00
    
    Payment Terms: Net 30
    Currency: USD
    """
    
    try:
        # Test extract_invoice_fields with normal input
        result = extract_invoice_fields(sample_ocr)
        
        assert result is not None, "extract_invoice_fields returned None"
        assert isinstance(result, dict), "Result should be a dictionary"
        
        # Verify all expected keys exist
        expected_keys = [
            'document_id', 'vendor_name', 'vendor_address', 'customer_name',
            'customer_address', 'invoice_date', 'due_date', 'total_amount',
            'tax_amount', 'currency'
        ]
        for key in expected_keys:
            assert key in result, f"Missing key: {key}"
        
        print(f"  ✓ extract_invoice_fields: returned dict with {len(result)} fields")
        print(f"    - document_id: {result['document_id']}")
        print(f"    - vendor_name: {result['vendor_name']}")
        print(f"    - customer_name: {result['customer_name']}")
        print(f"    - invoice_date: {result['invoice_date']}")
        print(f"    - due_date: {result['due_date']}")
        print(f"    - total_amount: {result['total_amount']}")
        print(f"    - tax_amount: {result['tax_amount']}")
        print(f"    - currency: {result['currency']}")
        
        # Validate specific extractions
        assert result['document_id'] == 'INV-2024-00123', f"Expected INV-2024-00123, got {result['document_id']}"
        assert result['vendor_name'] == 'Acme Corporation', f"Expected Acme Corporation, got {result['vendor_name']}"
        assert result['customer_name'] == 'John Smith', f"Expected John Smith, got {result['customer_name']}"
        assert result['invoice_date'] == '2024-01-15', f"Expected 2024-01-15, got {result['invoice_date']}"
        assert result['due_date'] == '2024-02-15', f"Expected 2024-02-15, got {result['due_date']}"
        assert result['total_amount'] == 432.00, f"Expected 432.00, got {result['total_amount']}"
        assert result['tax_amount'] == 32.00, f"Expected 32.00, got {result['tax_amount']}"
        assert result['currency'] == 'USD', f"Expected USD, got {result['currency']}"
        print("  ✓ All field values validated correctly")
        
        # Test edge case: OCR with errors
        ocr_with_errors = """
        ABC Company
        Invoice No: INV-OO123
        Date: 15/O1/2024
        Total: $1,234.56
        """
        result_ocr_errors = extract_invoice_fields(ocr_with_errors)
        assert result_ocr_errors['document_id'] is not None, "Should extract document_id with OCR errors"
        print(f"  ✓ OCR error handling: document_id={result_ocr_errors['document_id']}")
        
        # Test edge case: European format
        european_ocr = """
        Empresa S.L.
        Factura #FAC-2024-001
        Fecha: 15.01.2024
        Total: 1.234,56 €
        """
        result_european = extract_invoice_fields(european_ocr)
        assert result_european['currency'] == 'EUR', f"Should detect EUR, got {result_european['currency']}"
        print(f"  ✓ European format: currency={result_european['currency']}")
        
        # Test error handling: TypeError for non-string
        try:
            extract_invoice_fields(123)
            print("  ✗ Should have raised TypeError for non-string input")
            sys.exit(1)
        except TypeError as e:
            print(f"  ✓ TypeError correctly raised: {e}")
        
        # Test error handling: ValueError for empty string
        try:
            extract_invoice_fields("   ")
            print("  ✗ Should have raised ValueError for whitespace-only input")
            sys.exit(1)
        except ValueError as e:
            print(f"  ✓ ValueError correctly raised: {e}")
        
        # Test minimal OCR text
        minimal_ocr = "Invoice #12345\nTotal: $100"
        result_minimal = extract_invoice_fields(minimal_ocr)
        assert result_minimal['document_id'] == '12345', f"Expected 12345, got {result_minimal['document_id']}"
        assert result_minimal['total_amount'] == 100.0, f"Expected 100.0, got {result_minimal['total_amount']}"
        print(f"  ✓ Minimal OCR: document_id={result_minimal['document_id']}, total={result_minimal['total_amount']}")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        import traceback
        traceback.print_exc()
        sys.exit(1)
