"""Activity implementations for electrostatic_potential_energy_analysis.

Generated by CompiledAI Workflow Factory.
"""

from typing import Union


def calculate_electrostatic_potential_energy(charge: float, voltage: float) -> float:
    """Calculate electrostatic potential energy using U = q * V.
    
    Computes the electrostatic potential energy of a charged particle
    in an electric field given its charge and the voltage.
    
    Args:
        charge: The charge of the particle in Coulombs (can be positive,
            negative, or zero).
        voltage: The voltage field in Volts.
        
    Returns:
        The electrostatic potential energy in Joules (U = q * V).
        
    Raises:
        TypeError: If charge or voltage is not a numeric type.
    """
    # Input validation
    if not isinstance(charge, (int, float)):
        raise TypeError(f"charge must be a numeric type, got {type(charge).__name__}")
    if not isinstance(voltage, (int, float)):
        raise TypeError(f"voltage must be a numeric type, got {type(voltage).__name__}")
    
    # Calculate electrostatic potential energy: U = q * V
    potential_energy = charge * voltage
    
    return float(potential_energy)


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test proton potential energy (positive charge, positive voltage)
        proton_charge = 1.6e-19  # Coulombs
        proton_voltage = 500  # Volts
        proton_energy = calculate_electrostatic_potential_energy(proton_charge, proton_voltage)
        expected_proton = 1.6e-19 * 500  # 8e-17 J
        assert abs(proton_energy - expected_proton) < 1e-30, \
            f"Proton energy mismatch: {proton_energy} != {expected_proton}"
        print(f"  ✓ proton potential energy: {proton_energy} J")
        
        # Test electron potential energy (negative charge, positive voltage)
        electron_charge = -1.6e-19  # Coulombs
        electron_voltage = 1000  # Volts
        electron_energy = calculate_electrostatic_potential_energy(electron_charge, electron_voltage)
        expected_electron = -1.6e-19 * 1000  # -1.6e-16 J
        assert abs(electron_energy - expected_electron) < 1e-30, \
            f"Electron energy mismatch: {electron_energy} != {expected_electron}"
        print(f"  ✓ electron potential energy: {electron_energy} J")
        
        # Test neutron potential energy (zero charge)
        neutron_charge = 0.0  # Coulombs
        neutron_voltage = 2000  # Volts
        neutron_energy = calculate_electrostatic_potential_energy(neutron_charge, neutron_voltage)
        assert neutron_energy == 0.0, f"Neutron energy should be 0, got {neutron_energy}"
        print(f"  ✓ neutron potential energy: {neutron_energy} J")
        
        # Test edge case: zero voltage
        zero_voltage_energy = calculate_electrostatic_potential_energy(1.6e-19, 0)
        assert zero_voltage_energy == 0.0, f"Zero voltage should give 0 energy, got {zero_voltage_energy}"
        print(f"  ✓ zero voltage case: {zero_voltage_energy} J")
        
        # Test edge case: negative voltage
        negative_voltage_energy = calculate_electrostatic_potential_energy(1.6e-19, -100)
        expected_neg = 1.6e-19 * -100
        assert abs(negative_voltage_energy - expected_neg) < 1e-30, \
            f"Negative voltage mismatch: {negative_voltage_energy} != {expected_neg}"
        print(f"  ✓ negative voltage case: {negative_voltage_energy} J")
        
        # Test type validation - invalid charge
        try:
            calculate_electrostatic_potential_energy("invalid", 500)
            assert False, "Should have raised TypeError for invalid charge"
        except TypeError as e:
            assert "charge must be a numeric type" in str(e)
            print("  ✓ type validation for charge")
        
        # Test type validation - invalid voltage
        try:
            calculate_electrostatic_potential_energy(1.6e-19, "invalid")
            assert False, "Should have raised TypeError for invalid voltage"
        except TypeError as e:
            assert "voltage must be a numeric type" in str(e)
            print("  ✓ type validation for voltage")
        
        # Test with integer inputs (should work)
        int_result = calculate_electrostatic_potential_energy(1, 100)
        assert int_result == 100.0, f"Integer input failed: {int_result}"
        print(f"  ✓ integer inputs: {int_result} J")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
