"""Activity implementations for calculate_binomial_probability_dice.

Generated by CompiledAI Workflow Factory.
"""

from typing import Any
import math


def calc_binomial_probability(n: int, k: int, p: float) -> float:
    """Calculate the probability of getting k successes in n trials using binomial distribution.
    
    Uses the binomial probability formula: P(X=k) = C(n,k) * p^k * (1-p)^(n-k)
    where C(n,k) is the binomial coefficient "n choose k".
    
    Args:
        n: The number of trials (dice rolls). Must be a non-negative integer.
        k: The number of successes (sixes) desired. Must be a non-negative integer <= n.
        p: The probability of success (rolling a six) on each trial. Must be in [0, 1].
        
    Returns:
        The probability of getting exactly k successes in n trials.
        
    Raises:
        TypeError: If n or k is not an integer, or p is not a number.
        ValueError: If n < 0, k < 0, k > n, or p is not in [0, 1].
    """
    # Input validation for types
    if not isinstance(n, int):
        raise TypeError(f"n must be an integer, got {type(n).__name__}")
    if not isinstance(k, int):
        raise TypeError(f"k must be an integer, got {type(k).__name__}")
    if not isinstance(p, (int, float)):
        raise TypeError(f"p must be a number, got {type(p).__name__}")
    
    # Input validation for values
    if n < 0:
        raise ValueError(f"n must be non-negative, got {n}")
    if k < 0:
        raise ValueError(f"k must be non-negative, got {k}")
    if k > n:
        raise ValueError(f"k cannot be greater than n (k={k}, n={n})")
    if not 0 <= p <= 1:
        raise ValueError(f"p must be in range [0, 1], got {p}")
    
    # Edge cases
    if n == 0:
        return 1.0 if k == 0 else 0.0
    if p == 0:
        return 1.0 if k == 0 else 0.0
    if p == 1:
        return 1.0 if k == n else 0.0
    
    # Calculate binomial coefficient C(n, k) = n! / (k! * (n-k)!)
    binomial_coefficient = math.comb(n, k)
    
    # Calculate probability using binomial formula: C(n,k) * p^k * (1-p)^(n-k)
    probability = binomial_coefficient * (p ** k) * ((1 - p) ** (n - k))
    
    return probability


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Default workflow values (n=20, k=5, p=0.6)
        result1 = calc_binomial_probability(20, 5, 0.6)
        assert isinstance(result1, float), "Result should be a float"
        assert 0 <= result1 <= 1, f"Probability must be in [0, 1], got {result1}"
        print(f"  ✓ calc_binomial_probability(20, 5, 0.6): {result1:.6f}")
        
        # Test 2: Simple case - coin flip, exactly 1 head in 2 flips
        # P(X=1) = C(2,1) * 0.5^1 * 0.5^1 = 2 * 0.25 = 0.5
        result2 = calc_binomial_probability(2, 1, 0.5)
        assert abs(result2 - 0.5) < 1e-10, f"Expected 0.5, got {result2}"
        print(f"  ✓ calc_binomial_probability(2, 1, 0.5): {result2} (expected 0.5)")
        
        # Test 3: Edge case - k=0 (no successes)
        # P(X=0) = C(5,0) * 0.3^0 * 0.7^5 = 1 * 1 * 0.16807 = 0.16807
        result3 = calc_binomial_probability(5, 0, 0.3)
        expected3 = 0.7 ** 5
        assert abs(result3 - expected3) < 1e-10, f"Expected {expected3}, got {result3}"
        print(f"  ✓ calc_binomial_probability(5, 0, 0.3): {result3:.6f}")
        
        # Test 4: Edge case - k=n (all successes)
        # P(X=3) = C(3,3) * 0.4^3 * 0.6^0 = 1 * 0.064 * 1 = 0.064
        result4 = calc_binomial_probability(3, 3, 0.4)
        expected4 = 0.4 ** 3
        assert abs(result4 - expected4) < 1e-10, f"Expected {expected4}, got {result4}"
        print(f"  ✓ calc_binomial_probability(3, 3, 0.4): {result4:.6f}")
        
        # Test 5: Edge case - n=0, k=0
        result5 = calc_binomial_probability(0, 0, 0.5)
        assert result5 == 1.0, f"Expected 1.0 for n=0, k=0, got {result5}"
        print(f"  ✓ calc_binomial_probability(0, 0, 0.5): {result5}")
        
        # Test 6: Edge case - p=0
        result6 = calc_binomial_probability(5, 0, 0.0)
        assert result6 == 1.0, f"Expected 1.0 when p=0 and k=0, got {result6}"
        print(f"  ✓ calc_binomial_probability(5, 0, 0.0): {result6}")
        
        # Test 7: Edge case - p=1
        result7 = calc_binomial_probability(5, 5, 1.0)
        assert result7 == 1.0, f"Expected 1.0 when p=1 and k=n, got {result7}"
        print(f"  ✓ calc_binomial_probability(5, 5, 1.0): {result7}")
        
        # Test 8: Type error for n
        try:
            calc_binomial_probability(5.5, 2, 0.5)
            assert False, "Should have raised TypeError for float n"
        except TypeError as e:
            assert "n must be an integer" in str(e)
            print(f"  ✓ TypeError raised for float n")
        
        # Test 9: ValueError for k > n
        try:
            calc_binomial_probability(5, 10, 0.5)
            assert False, "Should have raised ValueError for k > n"
        except ValueError as e:
            assert "k cannot be greater than n" in str(e)
            print(f"  ✓ ValueError raised for k > n")
        
        # Test 10: ValueError for invalid probability
        try:
            calc_binomial_probability(5, 2, 1.5)
            assert False, "Should have raised ValueError for p > 1"
        except ValueError as e:
            assert "p must be in range" in str(e)
            print(f"  ✓ ValueError raised for p > 1")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
