"""Activity implementations for calculate_object_displacement.

Generated by CompiledAI Workflow Factory.
"""

from typing import Union


def calculate_displacement(
    initial_velocity: float,
    acceleration: float,
    time: float
) -> float:
    """Calculate the displacement of an object given initial velocity, acceleration, and time.
    
    Uses the kinematic equation: d = v₀t + ½at²
    where d is displacement, v₀ is initial velocity, a is acceleration, and t is time.
    
    Args:
        initial_velocity: The initial velocity of the object, in meters per second (m/s)
        acceleration: The acceleration of the object, in meters per second squared (m/s²)
        time: The time the object has been moving, in seconds
        
    Returns:
        The calculated displacement of the object in meters
        
    Raises:
        TypeError: If any parameter is not a numeric type (int or float)
        ValueError: If time is negative
    """
    # Input validation - type checking
    for param_name, param_value in [
        ("initial_velocity", initial_velocity),
        ("acceleration", acceleration),
        ("time", time)
    ]:
        if not isinstance(param_value, (int, float)):
            raise TypeError(
                f"{param_name} must be a numeric type (int or float), "
                f"got {type(param_value).__name__}"
            )
    
    # Validate time is non-negative
    if time < 0:
        raise ValueError(f"time must be non-negative, got {time}")
    
    # Calculate displacement using kinematic equation: d = v₀t + ½at²
    displacement = (initial_velocity * time) + (0.5 * acceleration * time ** 2)
    
    return displacement


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Basic calculation with default values from workflow spec
        result1 = calculate_displacement(
            initial_velocity=15.0,
            acceleration=9.8,
            time=10.0
        )
        # Expected: 15.0 * 10.0 + 0.5 * 9.8 * 10.0² = 150 + 490 = 640
        expected1 = 640.0
        assert abs(result1 - expected1) < 1e-9, f"Expected {expected1}, got {result1}"
        print(f"  ✓ calculate_displacement(15.0, 9.8, 10.0): {result1}")
        
        # Test 2: Zero initial velocity (free fall from rest)
        result2 = calculate_displacement(
            initial_velocity=0.0,
            acceleration=9.8,
            time=5.0
        )
        # Expected: 0 + 0.5 * 9.8 * 25 = 122.5
        expected2 = 122.5
        assert abs(result2 - expected2) < 1e-9, f"Expected {expected2}, got {result2}"
        print(f"  ✓ calculate_displacement(0.0, 9.8, 5.0): {result2}")
        
        # Test 3: Zero acceleration (constant velocity)
        result3 = calculate_displacement(
            initial_velocity=20.0,
            acceleration=0.0,
            time=10.0
        )
        # Expected: 20 * 10 + 0 = 200
        expected3 = 200.0
        assert abs(result3 - expected3) < 1e-9, f"Expected {expected3}, got {result3}"
        print(f"  ✓ calculate_displacement(20.0, 0.0, 10.0): {result3}")
        
        # Test 4: Negative acceleration (deceleration)
        result4 = calculate_displacement(
            initial_velocity=30.0,
            acceleration=-5.0,
            time=4.0
        )
        # Expected: 30 * 4 + 0.5 * (-5) * 16 = 120 - 40 = 80
        expected4 = 80.0
        assert abs(result4 - expected4) < 1e-9, f"Expected {expected4}, got {result4}"
        print(f"  ✓ calculate_displacement(30.0, -5.0, 4.0): {result4}")
        
        # Test 5: Zero time
        result5 = calculate_displacement(
            initial_velocity=10.0,
            acceleration=9.8,
            time=0.0
        )
        expected5 = 0.0
        assert abs(result5 - expected5) < 1e-9, f"Expected {expected5}, got {result5}"
        print(f"  ✓ calculate_displacement(10.0, 9.8, 0.0): {result5}")
        
        # Test 6: Integer inputs (should work due to duck typing)
        result6 = calculate_displacement(
            initial_velocity=10,
            acceleration=2,
            time=5
        )
        # Expected: 10 * 5 + 0.5 * 2 * 25 = 50 + 25 = 75
        expected6 = 75.0
        assert abs(result6 - expected6) < 1e-9, f"Expected {expected6}, got {result6}"
        print(f"  ✓ calculate_displacement(10, 2, 5) with ints: {result6}")
        
        # Test 7: TypeError for invalid input type
        try:
            calculate_displacement("10.0", 9.8, 10.0)
            assert False, "Should have raised TypeError for string input"
        except TypeError as e:
            assert "initial_velocity" in str(e), f"Error should mention parameter name: {e}"
            print(f"  ✓ TypeError raised for string input: {e}")
        
        # Test 8: ValueError for negative time
        try:
            calculate_displacement(15.0, 9.8, -5.0)
            assert False, "Should have raised ValueError for negative time"
        except ValueError as e:
            assert "time" in str(e), f"Error should mention time: {e}"
            print(f"  ✓ ValueError raised for negative time: {e}")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
