"""Activity implementations for projectile_displacement_calculation.

Generated by CompiledAI Workflow Factory.
"""

from typing import Union


def calculate_displacement(
    initial_velocity: float,
    acceleration: float,
    time: float
) -> float:
    """Calculate the displacement of a projectile using kinematic equation.
    
    Uses the formula: displacement = initial_velocity * time + 0.5 * acceleration * time²
    
    Args:
        initial_velocity: The initial velocity of the projectile in meters per second.
        acceleration: The acceleration of the projectile in meters per second squared
            (negative for downward, e.g., -9.8 m/s² for gravity).
        time: The duration of motion in seconds.
        
    Returns:
        The displacement of the projectile in meters.
        
    Raises:
        TypeError: If any parameter is not a numeric type (int or float).
        ValueError: If time is negative.
    """
    # Input validation - type checks
    if not isinstance(initial_velocity, (int, float)):
        raise TypeError(
            f"initial_velocity must be a number, got {type(initial_velocity).__name__}"
        )
    if not isinstance(acceleration, (int, float)):
        raise TypeError(
            f"acceleration must be a number, got {type(acceleration).__name__}"
        )
    if not isinstance(time, (int, float)):
        raise TypeError(
            f"time must be a number, got {type(time).__name__}"
        )
    
    # Value validation
    if time < 0:
        raise ValueError(f"time must be non-negative, got {time}")
    
    # Calculate displacement using kinematic equation:
    # s = v₀t + ½at²
    displacement = initial_velocity * time + 0.5 * acceleration * time ** 2
    
    return float(displacement)


# Test block - REQUIRED
if __name__ == "__main__":
    import sys
    
    print("Testing activities...")
    
    try:
        # Test 1: Stone displacement (v₀=20, a=-9.8, t=5)
        # Expected: 20*5 + 0.5*(-9.8)*25 = 100 - 122.5 = -22.5
        stone_displacement = calculate_displacement(20.0, -9.8, 5.0)
        expected_stone = 20.0 * 5.0 + 0.5 * (-9.8) * 5.0 ** 2
        assert abs(stone_displacement - expected_stone) < 1e-9, \
            f"Stone displacement mismatch: got {stone_displacement}, expected {expected_stone}"
        print(f"  ✓ calculate_displacement (stone): {stone_displacement} m")
        
        # Test 2: Rubber ball displacement (v₀=30, a=-9.8, t=5)
        # Expected: 30*5 + 0.5*(-9.8)*25 = 150 - 122.5 = 27.5
        rubber_ball_displacement = calculate_displacement(30.0, -9.8, 5.0)
        expected_rubber = 30.0 * 5.0 + 0.5 * (-9.8) * 5.0 ** 2
        assert abs(rubber_ball_displacement - expected_rubber) < 1e-9, \
            f"Rubber ball displacement mismatch: got {rubber_ball_displacement}, expected {expected_rubber}"
        print(f"  ✓ calculate_displacement (rubber ball): {rubber_ball_displacement} m")
        
        # Test 3: Metal ball displacement (v₀=25, a=-9.8, t=5)
        # Expected: 25*5 + 0.5*(-9.8)*25 = 125 - 122.5 = 2.5
        metal_ball_displacement = calculate_displacement(25.0, -9.8, 5.0)
        expected_metal = 25.0 * 5.0 + 0.5 * (-9.8) * 5.0 ** 2
        assert abs(metal_ball_displacement - expected_metal) < 1e-9, \
            f"Metal ball displacement mismatch: got {metal_ball_displacement}, expected {expected_metal}"
        print(f"  ✓ calculate_displacement (metal ball): {metal_ball_displacement} m")
        
        # Test 4: Edge case - zero time
        zero_time_result = calculate_displacement(20.0, -9.8, 0.0)
        assert zero_time_result == 0.0, f"Zero time should give zero displacement, got {zero_time_result}"
        print(f"  ✓ calculate_displacement (zero time): {zero_time_result} m")
        
        # Test 5: Edge case - zero velocity (free fall)
        free_fall = calculate_displacement(0.0, -9.8, 5.0)
        expected_free_fall = 0.5 * (-9.8) * 25.0
        assert abs(free_fall - expected_free_fall) < 1e-9, \
            f"Free fall mismatch: got {free_fall}, expected {expected_free_fall}"
        print(f"  ✓ calculate_displacement (free fall): {free_fall} m")
        
        # Test 6: Edge case - no acceleration (uniform motion)
        uniform_motion = calculate_displacement(10.0, 0.0, 5.0)
        assert uniform_motion == 50.0, f"Uniform motion mismatch: got {uniform_motion}, expected 50.0"
        print(f"  ✓ calculate_displacement (uniform motion): {uniform_motion} m")
        
        # Test 7: Integer inputs should work
        int_result = calculate_displacement(20, -10, 5)
        assert isinstance(int_result, float), "Result should be float even with int inputs"
        print(f"  ✓ calculate_displacement (integer inputs): {int_result} m")
        
        # Test 8: Type error for invalid input
        try:
            calculate_displacement("20", -9.8, 5.0)
            assert False, "Should have raised TypeError for string input"
        except TypeError as e:
            assert "initial_velocity must be a number" in str(e)
            print("  ✓ calculate_displacement (type error): Correctly raised TypeError")
        
        # Test 9: Value error for negative time
        try:
            calculate_displacement(20.0, -9.8, -5.0)
            assert False, "Should have raised ValueError for negative time"
        except ValueError as e:
            assert "time must be non-negative" in str(e)
            print("  ✓ calculate_displacement (negative time): Correctly raised ValueError")
        
        print("\nAll tests passed! ✅")
        
    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
