"""Activity implementations for calculate_object_densities.

Generated by CompiledAI Workflow Factory.
"""

from typing import Any


def calculate_density(mass: float, volume: float) -> float:
    """Calculate the density of an object given its mass and volume.

    Mass must be provided in kilograms, volume in cubic meters.
    Returns density in kg/m³.

    Args:
        mass: The mass of the object in kilograms
        volume: The volume of the object in cubic meters

    Returns:
        The density of the object in kg/m³

    Raises:
        TypeError: If mass or volume is not a number
        ValueError: If mass is negative or volume is non-positive
    """
    # Input validation - type checking
    if not isinstance(mass, (int, float)):
        raise TypeError(f"mass must be a number, got {type(mass).__name__}")
    if not isinstance(volume, (int, float)):
        raise TypeError(f"volume must be a number, got {type(volume).__name__}")

    # Convert to float for consistent arithmetic
    mass = float(mass)
    volume = float(volume)

    # Value validation
    if mass < 0:
        raise ValueError(f"mass must be non-negative, got {mass}")
    if volume <= 0:
        raise ValueError(f"volume must be positive, got {volume}")

    # Calculate density
    density = mass / volume

    return density


# Test block - REQUIRED
if __name__ == "__main__":
    import sys

    print("Testing activities...")

    try:
        # Test calculate_density with normal values
        # Using SI units: 5 kg / 0.001 m³ = 5000 kg/m³
        result1 = calculate_density(5.0, 0.001)
        assert result1 == 5000.0, f"Expected 5000.0, got {result1}"
        print(f"  ✓ calculate_density(5.0, 0.001): {result1} kg/m³")

        # Test with sample data from workflow (converted to SI units)
        # metal_cube: 500g = 0.5kg, 100cc = 0.0001m³
        mass_kg = 0.5  # 500 grams to kg
        volume_m3 = 0.0001  # 100 cc to m³
        result2 = calculate_density(mass_kg, volume_m3)
        assert result2 == 5000.0, f"Expected 5000.0, got {result2}"
        print(f"  ✓ calculate_density(0.5, 0.0001) [metal_cube]: {result2} kg/m³")

        # Test with integer inputs
        result3 = calculate_density(10, 2)
        assert result3 == 5.0, f"Expected 5.0, got {result3}"
        print(f"  ✓ calculate_density(10, 2): {result3} kg/m³")

        # Test with zero mass (valid edge case)
        result4 = calculate_density(0, 1.0)
        assert result4 == 0.0, f"Expected 0.0, got {result4}"
        print(f"  ✓ calculate_density(0, 1.0): {result4} kg/m³")

        # Test edge case: negative mass
        try:
            calculate_density(-5.0, 0.001)
            print("  ✗ calculate_density(-5.0, 0.001) should raise ValueError")
            sys.exit(1)
        except ValueError as e:
            print(f"  ✓ calculate_density(-5.0, 0.001) raised ValueError: {e}")

        # Test edge case: zero volume
        try:
            calculate_density(5.0, 0)
            print("  ✗ calculate_density(5.0, 0) should raise ValueError")
            sys.exit(1)
        except ValueError as e:
            print(f"  ✓ calculate_density(5.0, 0) raised ValueError: {e}")

        # Test edge case: negative volume
        try:
            calculate_density(5.0, -0.001)
            print("  ✗ calculate_density(5.0, -0.001) should raise ValueError")
            sys.exit(1)
        except ValueError as e:
            print(f"  ✓ calculate_density(5.0, -0.001) raised ValueError: {e}")

        # Test edge case: invalid type for mass
        try:
            calculate_density("5.0", 0.001)
            print("  ✗ calculate_density('5.0', 0.001) should raise TypeError")
            sys.exit(1)
        except TypeError as e:
            print(f"  ✓ calculate_density('5.0', 0.001) raised TypeError: {e}")

        # Test edge case: invalid type for volume
        try:
            calculate_density(5.0, None)
            print("  ✗ calculate_density(5.0, None) should raise TypeError")
            sys.exit(1)
        except TypeError as e:
            print(f"  ✓ calculate_density(5.0, None) raised TypeError: {e}")

        print("\nAll tests passed! ✅")

    except Exception as e:
        print(f"\nTest failed: {e} ❌")
        sys.exit(1)
